# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsMediaManagement.proto

require 'google/protobuf'


descriptor_data = "\n\x1e\x61nalyticsMediaManagement.proto\x12\x1crv.analytics.mediamanagement\"\xe2\x01\n\x14InstallationComplete\x12M\n\x07success\x18\x01 \x01(\x0b\x32:.rv.analytics.mediamanagement.InstallationComplete.SuccessH\x00\x12M\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32:.rv.analytics.mediamanagement.InstallationComplete.FailureH\x00\x1a\t\n\x07Success\x1a\x18\n\x07\x46\x61ilure\x12\r\n\x05\x65rror\x18\x01 \x01(\tB\x07\n\x05state\"\xe5\x01\n\x15\x42ootstrappingComplete\x12N\n\x07success\x18\x01 \x01(\x0b\x32;.rv.analytics.mediamanagement.BootstrappingComplete.SuccessH\x00\x12N\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32;.rv.analytics.mediamanagement.BootstrappingComplete.FailureH\x00\x1a\t\n\x07Success\x1a\x18\n\x07\x46\x61ilure\x12\r\n\x05\x65rror\x18\x01 \x01(\tB\x07\n\x05state\"\x1f\n\x0eMessageFailure\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\x18\n\x16UnexpectedlyNotRunning\"\x8f\x01\n\x11\x43onnectionChanged\x12\x44\n\x05state\x18\x01 \x01(\x0e\x32\x35.rv.analytics.mediamanagement.ConnectionChanged.State\"4\n\x05State\x12\x13\n\x0fSTATE_CONNECTED\x10\x00\x12\x16\n\x12STATE_DISCONNECTED\x10\x01\"4\n\x13\x41\x64\x64\x65\x64MediaReference\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x0f\n\rNotRespondingb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rv
  module Analytics
    module Mediamanagement
      InstallationComplete = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.InstallationComplete").msgclass
      InstallationComplete::Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.InstallationComplete.Success").msgclass
      InstallationComplete::Failure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.InstallationComplete.Failure").msgclass
      BootstrappingComplete = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.BootstrappingComplete").msgclass
      BootstrappingComplete::Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.BootstrappingComplete.Success").msgclass
      BootstrappingComplete::Failure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.BootstrappingComplete.Failure").msgclass
      MessageFailure = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.MessageFailure").msgclass
      UnexpectedlyNotRunning = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.UnexpectedlyNotRunning").msgclass
      ConnectionChanged = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.ConnectionChanged").msgclass
      ConnectionChanged::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.ConnectionChanged.State").enummodule
      AddedMediaReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.AddedMediaReference").msgclass
      NotResponding = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.analytics.mediamanagement.NotResponding").msgclass
    end
  end
end
