# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: font.proto

require 'google/protobuf'

require 'customOptions_pb'


descriptor_data = "\n\nfont.proto\x12\x07rv.data\x1a\x13\x63ustomOptions.proto\"^\n\x04\x46ont\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x01\x12\x0e\n\x06italic\x18\x04 \x01(\x08\x12\x0c\n\x04\x62old\x18\x08 \x01(\x08\x12\x0e\n\x06\x66\x61mily\x18\t \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\n \x01(\tb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rv
  module Data
    Font = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.data.Font").msgclass
  end
end
