# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proApiV1Miscellaneous.proto

require 'google/protobuf'


descriptor_data = "\n\x1bproApiV1Miscellaneous.proto\x12\x07rv.data\"\x84\x01\n\x1c\x41PI_v1_Miscellaneous_Request\x12J\n\rfind_my_mouse\x18\x01 \x01(\x0b\x32\x31.rv.data.API_v1_Miscellaneous_Request.FindMyMouseH\x00\x1a\r\n\x0b\x46indMyMouseB\t\n\x07Request\"\x87\x01\n\x1d\x41PI_v1_Miscellaneous_Response\x12K\n\rfind_my_mouse\x18\x01 \x01(\x0b\x32\x32.rv.data.API_v1_Miscellaneous_Response.FindMyMouseH\x00\x1a\r\n\x0b\x46indMyMouseB\n\n\x08Responseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rv
  module Data
    API_v1_Miscellaneous_Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.data.API_v1_Miscellaneous_Request").msgclass
    API_v1_Miscellaneous_Request::FindMyMouse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.data.API_v1_Miscellaneous_Request.FindMyMouse").msgclass
    API_v1_Miscellaneous_Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.data.API_v1_Miscellaneous_Response").msgclass
    API_v1_Miscellaneous_Response::FindMyMouse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rv.data.API_v1_Miscellaneous_Response.FindMyMouse").msgclass
  end
end
