// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ccli.proto
// Protobuf C++ Version: 6.33.4

#include "ccli.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rv {
namespace data {

inline constexpr CopyrightLayout_Token::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        token_type_{static_cast< ::rv::data::CopyrightLayout_TokenType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CopyrightLayout_Token::CopyrightLayout_Token(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CopyrightLayout_Token_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CopyrightLayout_TokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CopyrightLayout_TokenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CopyrightLayout_TokenDefaultTypeInternal() {}
  union {
    CopyrightLayout_Token _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CopyrightLayout_TokenDefaultTypeInternal _CopyrightLayout_Token_default_instance_;

inline constexpr CopyrightLayout::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tokens_{} {}

template <typename>
PROTOBUF_CONSTEXPR CopyrightLayout::CopyrightLayout(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CopyrightLayout_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CopyrightLayoutDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CopyrightLayoutDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CopyrightLayoutDefaultTypeInternal() {}
  union {
    CopyrightLayout _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CopyrightLayoutDefaultTypeInternal _CopyrightLayout_default_instance_;

inline constexpr CCLIDocument::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ccli_license_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        application_info_{nullptr},
        template__{nullptr},
        layout_{nullptr},
        enable_ccli_display_{false},
        display_type_{static_cast< ::rv::data::CCLIDocument_DisplayType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CCLIDocument::CCLIDocument(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CCLIDocument_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CCLIDocumentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CCLIDocumentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CCLIDocumentDefaultTypeInternal() {}
  union {
    CCLIDocument _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CCLIDocumentDefaultTypeInternal _CCLIDocument_default_instance_;
}  // namespace data
}  // namespace rv
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_ccli_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_ccli_2eproto = nullptr;
const ::uint32_t
    TableStruct_ccli_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.application_info_),
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.enable_ccli_display_),
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.ccli_license_),
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.display_type_),
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.template__),
        PROTOBUF_FIELD_OFFSET(::rv::data::CCLIDocument, _impl_.layout_),
        1,
        4,
        0,
        5,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rv::data::CopyrightLayout_Token, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rv::data::CopyrightLayout_Token, _impl_.token_type_),
        PROTOBUF_FIELD_OFFSET(::rv::data::CopyrightLayout_Token, _impl_.text_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::rv::data::CopyrightLayout, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::rv::data::CopyrightLayout, _impl_.tokens_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::rv::data::CCLIDocument)},
        {15, sizeof(::rv::data::CopyrightLayout_Token)},
        {22, sizeof(::rv::data::CopyrightLayout)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::rv::data::_CCLIDocument_default_instance_._instance,
    &::rv::data::_CopyrightLayout_Token_default_instance_._instance,
    &::rv::data::_CopyrightLayout_default_instance_._instance,
};
const char descriptor_table_protodef_ccli_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nccli.proto\022\007rv.data\032\025applicationInfo.p"
    "roto\032\023customOptions.proto\032\016template.prot"
    "o\"\222\003\n\014CCLIDocument\0222\n\020application_info\030\001"
    " \001(\0132\030.rv.data.ApplicationInfo\022\033\n\023enable"
    "_ccli_display\030\002 \001(\010\022\024\n\014ccli_license\030\003 \001("
    "\t\0227\n\014display_type\030\004 \001(\0162!.rv.data.CCLIDo"
    "cument.DisplayType\022)\n\010template\030\005 \001(\0132\027.r"
    "v.data.Template.Slide\022(\n\006layout\030\006 \001(\0132\030."
    "rv.data.CopyrightLayout\"\214\001\n\013DisplayType\022"
    "\034\n\030DISPLAY_TYPE_FIRST_SLIDE\020\000\022\033\n\027DISPLAY"
    "_TYPE_LAST_SLIDE\020\001\022%\n!DISPLAY_TYPE_FIRST"
    "_AND_LAST_SLIDE\020\002\022\033\n\027DISPLAY_TYPE_ALL_SL"
    "IDES\020\003\"\217\002\n\017CopyrightLayout\022.\n\006tokens\030\002 \003"
    "(\0132\036.rv.data.CopyrightLayout.Token\032M\n\005To"
    "ken\0226\n\ntoken_type\030\001 \001(\0162\".rv.data.Copyri"
    "ghtLayout.TokenType\022\014\n\004text\030\002 \001(\t\"}\n\tTok"
    "enType\022\010\n\004Text\020\000\022\n\n\006Artist\020\001\022\n\n\006Author\020\002"
    "\022\r\n\tPublisher\020\003\022\t\n\005Title\020\004\022\021\n\rCopyrightY"
    "ear\020\005\022\021\n\rLicenseNumber\020\006\022\016\n\nSongNumber\020\007"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_ccli_2eproto_deps[3] = {
        &::descriptor_table_applicationInfo_2eproto,
        &::descriptor_table_customOptions_2eproto,
        &::descriptor_table_template_2eproto,
};
static ::absl::once_flag descriptor_table_ccli_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ccli_2eproto = {
    false,
    false,
    768,
    descriptor_table_protodef_ccli_2eproto,
    "ccli.proto",
    &descriptor_table_ccli_2eproto_once,
    descriptor_table_ccli_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_ccli_2eproto::offsets,
    file_level_enum_descriptors_ccli_2eproto,
    file_level_service_descriptors_ccli_2eproto,
};
namespace rv {
namespace data {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CCLIDocument_DisplayType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ccli_2eproto);
  return file_level_enum_descriptors_ccli_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CCLIDocument_DisplayType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CopyrightLayout_TokenType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ccli_2eproto);
  return file_level_enum_descriptors_ccli_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t CopyrightLayout_TokenType_internal_data_[] = {
    524288u, 0u, };
// ===================================================================

class CCLIDocument::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CCLIDocument>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_._has_bits_);
};

void CCLIDocument::clear_application_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.application_info_ != nullptr) _impl_.application_info_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void CCLIDocument::clear_template_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.template__ != nullptr) _impl_.template__->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
CCLIDocument::CCLIDocument(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CCLIDocument_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rv.data.CCLIDocument)
}
PROTOBUF_NDEBUG_INLINE CCLIDocument::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rv::data::CCLIDocument& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ccli_license_(arena, from.ccli_license_) {}

CCLIDocument::CCLIDocument(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CCLIDocument& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CCLIDocument_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CCLIDocument* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.application_info_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.application_info_)
                : nullptr;
  _impl_.template__ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.template__)
                : nullptr;
  _impl_.layout_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.layout_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, enable_ccli_display_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, enable_ccli_display_),
           offsetof(Impl_, display_type_) -
               offsetof(Impl_, enable_ccli_display_) +
               sizeof(Impl_::display_type_));

  // @@protoc_insertion_point(copy_constructor:rv.data.CCLIDocument)
}
PROTOBUF_NDEBUG_INLINE CCLIDocument::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ccli_license_(arena) {}

inline void CCLIDocument::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, application_info_),
           0,
           offsetof(Impl_, display_type_) -
               offsetof(Impl_, application_info_) +
               sizeof(Impl_::display_type_));
}
CCLIDocument::~CCLIDocument() {
  // @@protoc_insertion_point(destructor:rv.data.CCLIDocument)
  SharedDtor(*this);
}
inline void CCLIDocument::SharedDtor(MessageLite& self) {
  CCLIDocument& this_ = static_cast<CCLIDocument&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ccli_license_.Destroy();
  delete this_._impl_.application_info_;
  delete this_._impl_.template__;
  delete this_._impl_.layout_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CCLIDocument::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CCLIDocument(arena);
}
constexpr auto CCLIDocument::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CCLIDocument),
                                            alignof(CCLIDocument));
}
constexpr auto CCLIDocument::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CCLIDocument_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CCLIDocument::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CCLIDocument>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CCLIDocument::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CCLIDocument>(), &CCLIDocument::ByteSizeLong,
              &CCLIDocument::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_._cached_size_),
          false,
      },
      &CCLIDocument::kDescriptorMethods,
      &descriptor_table_ccli_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CCLIDocument_class_data_ =
        CCLIDocument::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CCLIDocument::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CCLIDocument_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CCLIDocument_class_data_.tc_table);
  return CCLIDocument_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 3, 41, 2>
CCLIDocument::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CCLIDocument_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rv::data::CCLIDocument>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rv.data.ApplicationInfo application_info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.application_info_)}},
    // bool enable_ccli_display = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CCLIDocument, _impl_.enable_ccli_display_), 4>(),
     {16, 4, 0,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.enable_ccli_display_)}},
    // string ccli_license = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.ccli_license_)}},
    // .rv.data.CCLIDocument.DisplayType display_type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CCLIDocument, _impl_.display_type_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.display_type_)}},
    // .rv.data.Template.Slide template = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 1,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.template__)}},
    // .rv.data.CopyrightLayout layout = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 3, 2,
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.layout_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .rv.data.ApplicationInfo application_info = 1;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.application_info_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool enable_ccli_display = 2;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.enable_ccli_display_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string ccli_license = 3;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.ccli_license_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .rv.data.CCLIDocument.DisplayType display_type = 4;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.display_type_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .rv.data.Template.Slide template = 5;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.template__), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .rv.data.CopyrightLayout layout = 6;
    {PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.layout_), _Internal::kHasBitsOffset + 3, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rv::data::ApplicationInfo>()},
      {::_pbi::TcParser::GetTable<::rv::data::Template_Slide>()},
      {::_pbi::TcParser::GetTable<::rv::data::CopyrightLayout>()},
  }},
  {{
    "\24\0\0\14\0\0\0\0"
    "rv.data.CCLIDocument"
    "ccli_license"
  }},
};
PROTOBUF_NOINLINE void CCLIDocument::Clear() {
// @@protoc_insertion_point(message_clear_start:rv.data.CCLIDocument)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.ccli_license_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.application_info_ != nullptr);
      _impl_.application_info_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.template__ != nullptr);
      _impl_.template__->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.layout_ != nullptr);
      _impl_.layout_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    ::memset(&_impl_.enable_ccli_display_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.display_type_) -
        reinterpret_cast<char*>(&_impl_.enable_ccli_display_)) + sizeof(_impl_.display_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CCLIDocument::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CCLIDocument& this_ = static_cast<const CCLIDocument&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CCLIDocument::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CCLIDocument& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rv.data.CCLIDocument)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .rv.data.ApplicationInfo application_info = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.application_info_, this_._impl_.application_info_->GetCachedSize(), target,
        stream);
  }

  // bool enable_ccli_display = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_enable_ccli_display() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_enable_ccli_display(), target);
    }
  }

  // string ccli_license = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ccli_license().empty()) {
      const ::std::string& _s = this_._internal_ccli_license();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rv.data.CCLIDocument.ccli_license");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // .rv.data.CCLIDocument.DisplayType display_type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_display_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_display_type(), target);
    }
  }

  // .rv.data.Template.Slide template = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.template__, this_._impl_.template__->GetCachedSize(), target,
        stream);
  }

  // .rv.data.CopyrightLayout layout = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.layout_, this_._impl_.layout_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rv.data.CCLIDocument)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CCLIDocument::ByteSizeLong(const MessageLite& base) {
  const CCLIDocument& this_ = static_cast<const CCLIDocument&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CCLIDocument::ByteSizeLong() const {
  const CCLIDocument& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rv.data.CCLIDocument)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string ccli_license = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ccli_license().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ccli_license());
      }
    }
    // .rv.data.ApplicationInfo application_info = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.application_info_);
    }
    // .rv.data.Template.Slide template = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.template__);
    }
    // .rv.data.CopyrightLayout layout = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.layout_);
    }
    // bool enable_ccli_display = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_enable_ccli_display() != 0) {
        total_size += 2;
      }
    }
    // .rv.data.CCLIDocument.DisplayType display_type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_display_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_display_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CCLIDocument::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CCLIDocument*>(&to_msg);
  auto& from = static_cast<const CCLIDocument&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rv.data.CCLIDocument)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ccli_license().empty()) {
        _this->_internal_set_ccli_license(from._internal_ccli_license());
      } else {
        if (_this->_impl_.ccli_license_.IsDefault()) {
          _this->_internal_set_ccli_license("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.application_info_ != nullptr);
      if (_this->_impl_.application_info_ == nullptr) {
        _this->_impl_.application_info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.application_info_);
      } else {
        _this->_impl_.application_info_->MergeFrom(*from._impl_.application_info_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.template__ != nullptr);
      if (_this->_impl_.template__ == nullptr) {
        _this->_impl_.template__ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.template__);
      } else {
        _this->_impl_.template__->MergeFrom(*from._impl_.template__);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.layout_ != nullptr);
      if (_this->_impl_.layout_ == nullptr) {
        _this->_impl_.layout_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.layout_);
      } else {
        _this->_impl_.layout_->MergeFrom(*from._impl_.layout_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_enable_ccli_display() != 0) {
        _this->_impl_.enable_ccli_display_ = from._impl_.enable_ccli_display_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_display_type() != 0) {
        _this->_impl_.display_type_ = from._impl_.display_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CCLIDocument::CopyFrom(const CCLIDocument& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rv.data.CCLIDocument)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CCLIDocument::InternalSwap(CCLIDocument* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ccli_license_, &other->_impl_.ccli_license_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.display_type_)
      + sizeof(CCLIDocument::_impl_.display_type_)
      - PROTOBUF_FIELD_OFFSET(CCLIDocument, _impl_.application_info_)>(
          reinterpret_cast<char*>(&_impl_.application_info_),
          reinterpret_cast<char*>(&other->_impl_.application_info_));
}

::google::protobuf::Metadata CCLIDocument::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CopyrightLayout_Token::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CopyrightLayout_Token>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_._has_bits_);
};

CopyrightLayout_Token::CopyrightLayout_Token(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CopyrightLayout_Token_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rv.data.CopyrightLayout.Token)
}
PROTOBUF_NDEBUG_INLINE CopyrightLayout_Token::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rv::data::CopyrightLayout_Token& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        text_(arena, from.text_) {}

CopyrightLayout_Token::CopyrightLayout_Token(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CopyrightLayout_Token& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CopyrightLayout_Token_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CopyrightLayout_Token* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.token_type_ = from._impl_.token_type_;

  // @@protoc_insertion_point(copy_constructor:rv.data.CopyrightLayout.Token)
}
PROTOBUF_NDEBUG_INLINE CopyrightLayout_Token::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        text_(arena) {}

inline void CopyrightLayout_Token::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.token_type_ = {};
}
CopyrightLayout_Token::~CopyrightLayout_Token() {
  // @@protoc_insertion_point(destructor:rv.data.CopyrightLayout.Token)
  SharedDtor(*this);
}
inline void CopyrightLayout_Token::SharedDtor(MessageLite& self) {
  CopyrightLayout_Token& this_ = static_cast<CopyrightLayout_Token&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CopyrightLayout_Token::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CopyrightLayout_Token(arena);
}
constexpr auto CopyrightLayout_Token::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CopyrightLayout_Token),
                                            alignof(CopyrightLayout_Token));
}
constexpr auto CopyrightLayout_Token::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CopyrightLayout_Token_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CopyrightLayout_Token::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CopyrightLayout_Token>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CopyrightLayout_Token::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CopyrightLayout_Token>(), &CopyrightLayout_Token::ByteSizeLong,
              &CopyrightLayout_Token::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_._cached_size_),
          false,
      },
      &CopyrightLayout_Token::kDescriptorMethods,
      &descriptor_table_ccli_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CopyrightLayout_Token_class_data_ =
        CopyrightLayout_Token::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CopyrightLayout_Token::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CopyrightLayout_Token_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CopyrightLayout_Token_class_data_.tc_table);
  return CopyrightLayout_Token_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2>
CopyrightLayout_Token::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CopyrightLayout_Token_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rv::data::CopyrightLayout_Token>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_.text_)}},
    // .rv.data.CopyrightLayout.TokenType token_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CopyrightLayout_Token, _impl_.token_type_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_.token_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rv.data.CopyrightLayout.TokenType token_type = 1;
    {PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_.token_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string text = 2;
    {PROTOBUF_FIELD_OFFSET(CopyrightLayout_Token, _impl_.text_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\0\4\0\0\0\0\0"
    "rv.data.CopyrightLayout.Token"
    "text"
  }},
};
PROTOBUF_NOINLINE void CopyrightLayout_Token::Clear() {
// @@protoc_insertion_point(message_clear_start:rv.data.CopyrightLayout.Token)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.text_.ClearNonDefaultToEmpty();
  }
  _impl_.token_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CopyrightLayout_Token::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CopyrightLayout_Token& this_ = static_cast<const CopyrightLayout_Token&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CopyrightLayout_Token::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CopyrightLayout_Token& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rv.data.CopyrightLayout.Token)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .rv.data.CopyrightLayout.TokenType token_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_token_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_token_type(), target);
    }
  }

  // string text = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_text().empty()) {
      const ::std::string& _s = this_._internal_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rv.data.CopyrightLayout.Token.text");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rv.data.CopyrightLayout.Token)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CopyrightLayout_Token::ByteSizeLong(const MessageLite& base) {
  const CopyrightLayout_Token& this_ = static_cast<const CopyrightLayout_Token&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CopyrightLayout_Token::ByteSizeLong() const {
  const CopyrightLayout_Token& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rv.data.CopyrightLayout.Token)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string text = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_text());
      }
    }
    // .rv.data.CopyrightLayout.TokenType token_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_token_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_token_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CopyrightLayout_Token::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CopyrightLayout_Token*>(&to_msg);
  auto& from = static_cast<const CopyrightLayout_Token&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:rv.data.CopyrightLayout.Token)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_text().empty()) {
        _this->_internal_set_text(from._internal_text());
      } else {
        if (_this->_impl_.text_.IsDefault()) {
          _this->_internal_set_text("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_token_type() != 0) {
        _this->_impl_.token_type_ = from._impl_.token_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CopyrightLayout_Token::CopyFrom(const CopyrightLayout_Token& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rv.data.CopyrightLayout.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CopyrightLayout_Token::InternalSwap(CopyrightLayout_Token* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  swap(_impl_.token_type_, other->_impl_.token_type_);
}

::google::protobuf::Metadata CopyrightLayout_Token::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CopyrightLayout::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CopyrightLayout>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_._has_bits_);
};

CopyrightLayout::CopyrightLayout(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CopyrightLayout_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rv.data.CopyrightLayout)
}
PROTOBUF_NDEBUG_INLINE CopyrightLayout::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::rv::data::CopyrightLayout& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tokens_{visibility, arena, from.tokens_} {}

CopyrightLayout::CopyrightLayout(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CopyrightLayout& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CopyrightLayout_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CopyrightLayout* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:rv.data.CopyrightLayout)
}
PROTOBUF_NDEBUG_INLINE CopyrightLayout::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tokens_{visibility, arena} {}

inline void CopyrightLayout::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CopyrightLayout::~CopyrightLayout() {
  // @@protoc_insertion_point(destructor:rv.data.CopyrightLayout)
  SharedDtor(*this);
}
inline void CopyrightLayout::SharedDtor(MessageLite& self) {
  CopyrightLayout& this_ = static_cast<CopyrightLayout&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CopyrightLayout::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CopyrightLayout(arena);
}
constexpr auto CopyrightLayout::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_.tokens_) +
          decltype(CopyrightLayout::_impl_.tokens_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CopyrightLayout), alignof(CopyrightLayout), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CopyrightLayout::PlacementNew_,
                                 sizeof(CopyrightLayout),
                                 alignof(CopyrightLayout));
  }
}
constexpr auto CopyrightLayout::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CopyrightLayout_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CopyrightLayout::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CopyrightLayout>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CopyrightLayout::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CopyrightLayout>(), &CopyrightLayout::ByteSizeLong,
              &CopyrightLayout::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_._cached_size_),
          false,
      },
      &CopyrightLayout::kDescriptorMethods,
      &descriptor_table_ccli_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CopyrightLayout_class_data_ =
        CopyrightLayout::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CopyrightLayout::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CopyrightLayout_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CopyrightLayout_class_data_.tc_table);
  return CopyrightLayout_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CopyrightLayout::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CopyrightLayout_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::rv::data::CopyrightLayout>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .rv.data.CopyrightLayout.Token tokens = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_.tokens_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .rv.data.CopyrightLayout.Token tokens = 2;
    {PROTOBUF_FIELD_OFFSET(CopyrightLayout, _impl_.tokens_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::rv::data::CopyrightLayout_Token>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CopyrightLayout::Clear() {
// @@protoc_insertion_point(message_clear_start:rv.data.CopyrightLayout)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.tokens_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CopyrightLayout::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CopyrightLayout& this_ = static_cast<const CopyrightLayout&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CopyrightLayout::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CopyrightLayout& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:rv.data.CopyrightLayout)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .rv.data.CopyrightLayout.Token tokens = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_tokens_size());
         i < n; i++) {
      const auto& repfield = this_._internal_tokens().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rv.data.CopyrightLayout)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CopyrightLayout::ByteSizeLong(const MessageLite& base) {
  const CopyrightLayout& this_ = static_cast<const CopyrightLayout&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CopyrightLayout::ByteSizeLong() const {
  const CopyrightLayout& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:rv.data.CopyrightLayout)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .rv.data.CopyrightLayout.Token tokens = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_tokens_size();
      for (const auto& msg : this_._internal_tokens()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CopyrightLayout::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CopyrightLayout*>(&to_msg);
  auto& from = static_cast<const CopyrightLayout&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:rv.data.CopyrightLayout)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_tokens()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_tokens());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CopyrightLayout::CopyFrom(const CopyrightLayout& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:rv.data.CopyrightLayout)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CopyrightLayout::InternalSwap(CopyrightLayout* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.tokens_.InternalSwap(&other->_impl_.tokens_);
}

::google::protobuf::Metadata CopyrightLayout::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace rv
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ccli_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
