// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: document.notifications.proto
// Protobuf C++ Version: 6.33.4

#ifndef document_2enotifications_2eproto_2epb_2eh
#define document_2enotifications_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_document_2enotifications_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_document_2enotifications_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_document_2enotifications_2eproto;
}  // extern "C"
namespace document {
class Notification;
struct NotificationDefaultTypeInternal;
extern NotificationDefaultTypeInternal _Notification_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Notification_class_data_;
class Notification_Available;
struct Notification_AvailableDefaultTypeInternal;
extern Notification_AvailableDefaultTypeInternal _Notification_Available_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Notification_Available_class_data_;
class Notification_Patch;
struct Notification_PatchDefaultTypeInternal;
extern Notification_PatchDefaultTypeInternal _Notification_Patch_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Notification_Patch_class_data_;
class Notification_Required;
struct Notification_RequiredDefaultTypeInternal;
extern Notification_RequiredDefaultTypeInternal _Notification_Required_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Notification_Required_class_data_;
class Notification_UnsubscribeComplete;
struct Notification_UnsubscribeCompleteDefaultTypeInternal;
extern Notification_UnsubscribeCompleteDefaultTypeInternal _Notification_UnsubscribeComplete_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Notification_UnsubscribeComplete_class_data_;
}  // namespace document
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace document {

// ===================================================================


// -------------------------------------------------------------------

class Notification_UnsubscribeComplete final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:document.Notification.UnsubscribeComplete) */ {
 public:
  inline Notification_UnsubscribeComplete() : Notification_UnsubscribeComplete(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Notification_UnsubscribeComplete* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Notification_UnsubscribeComplete));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Notification_UnsubscribeComplete(::google::protobuf::internal::ConstantInitialized);

  inline Notification_UnsubscribeComplete(const Notification_UnsubscribeComplete& from) : Notification_UnsubscribeComplete(nullptr, from) {}
  inline Notification_UnsubscribeComplete(Notification_UnsubscribeComplete&& from) noexcept
      : Notification_UnsubscribeComplete(nullptr, ::std::move(from)) {}
  inline Notification_UnsubscribeComplete& operator=(const Notification_UnsubscribeComplete& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification_UnsubscribeComplete& operator=(Notification_UnsubscribeComplete&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification_UnsubscribeComplete& default_instance() {
    return *reinterpret_cast<const Notification_UnsubscribeComplete*>(
        &_Notification_UnsubscribeComplete_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Notification_UnsubscribeComplete& a, Notification_UnsubscribeComplete& b) { a.Swap(&b); }
  inline void Swap(Notification_UnsubscribeComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification_UnsubscribeComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification_UnsubscribeComplete* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Notification_UnsubscribeComplete>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Notification_UnsubscribeComplete& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Notification_UnsubscribeComplete& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "document.Notification.UnsubscribeComplete"; }

  explicit Notification_UnsubscribeComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Notification_UnsubscribeComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Notification_UnsubscribeComplete& from);
  Notification_UnsubscribeComplete(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Notification_UnsubscribeComplete&& from) noexcept
      : Notification_UnsubscribeComplete(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:document.Notification.UnsubscribeComplete)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_document_2enotifications_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Notification_UnsubscribeComplete_class_data_;
// -------------------------------------------------------------------

class Notification_Required final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:document.Notification.Required) */ {
 public:
  inline Notification_Required() : Notification_Required(nullptr) {}
  ~Notification_Required() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Notification_Required* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Notification_Required));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Notification_Required(::google::protobuf::internal::ConstantInitialized);

  inline Notification_Required(const Notification_Required& from) : Notification_Required(nullptr, from) {}
  inline Notification_Required(Notification_Required&& from) noexcept
      : Notification_Required(nullptr, ::std::move(from)) {}
  inline Notification_Required& operator=(const Notification_Required& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification_Required& operator=(Notification_Required&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification_Required& default_instance() {
    return *reinterpret_cast<const Notification_Required*>(
        &_Notification_Required_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Notification_Required& a, Notification_Required& b) { a.Swap(&b); }
  inline void Swap(Notification_Required* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification_Required* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification_Required* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Notification_Required>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Notification_Required& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Notification_Required& from) { Notification_Required::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Notification_Required* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "document.Notification.Required"; }

  explicit Notification_Required(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Notification_Required(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Notification_Required& from);
  Notification_Required(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Notification_Required&& from) noexcept
      : Notification_Required(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const ::std::string& uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uuid();
  void set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uuid();

  public:
  // @@protoc_insertion_point(class_scope:document.Notification.Required)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Notification_Required& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_document_2enotifications_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Notification_Required_class_data_;
// -------------------------------------------------------------------

class Notification_Patch final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:document.Notification.Patch) */ {
 public:
  inline Notification_Patch() : Notification_Patch(nullptr) {}
  ~Notification_Patch() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Notification_Patch* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Notification_Patch));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Notification_Patch(::google::protobuf::internal::ConstantInitialized);

  inline Notification_Patch(const Notification_Patch& from) : Notification_Patch(nullptr, from) {}
  inline Notification_Patch(Notification_Patch&& from) noexcept
      : Notification_Patch(nullptr, ::std::move(from)) {}
  inline Notification_Patch& operator=(const Notification_Patch& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification_Patch& operator=(Notification_Patch&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification_Patch& default_instance() {
    return *reinterpret_cast<const Notification_Patch*>(
        &_Notification_Patch_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Notification_Patch& a, Notification_Patch& b) { a.Swap(&b); }
  inline void Swap(Notification_Patch* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification_Patch* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification_Patch* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Notification_Patch>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Notification_Patch& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Notification_Patch& from) { Notification_Patch::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Notification_Patch* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "document.Notification.Patch"; }

  explicit Notification_Patch(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Notification_Patch(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Notification_Patch& from);
  Notification_Patch(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Notification_Patch&& from) noexcept
      : Notification_Patch(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kBlobFieldNumber = 2,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const ::std::string& uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uuid();
  void set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uuid();

  public:
  // bytes blob = 2;
  void clear_blob() ;
  const ::std::string& blob() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_blob(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_blob();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_blob();
  void set_allocated_blob(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_blob() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_blob(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_blob();

  public:
  // @@protoc_insertion_point(class_scope:document.Notification.Patch)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Notification_Patch& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr blob_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_document_2enotifications_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Notification_Patch_class_data_;
// -------------------------------------------------------------------

class Notification_Available final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:document.Notification.Available) */ {
 public:
  inline Notification_Available() : Notification_Available(nullptr) {}
  ~Notification_Available() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Notification_Available* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Notification_Available));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Notification_Available(::google::protobuf::internal::ConstantInitialized);

  inline Notification_Available(const Notification_Available& from) : Notification_Available(nullptr, from) {}
  inline Notification_Available(Notification_Available&& from) noexcept
      : Notification_Available(nullptr, ::std::move(from)) {}
  inline Notification_Available& operator=(const Notification_Available& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification_Available& operator=(Notification_Available&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification_Available& default_instance() {
    return *reinterpret_cast<const Notification_Available*>(
        &_Notification_Available_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Notification_Available& a, Notification_Available& b) { a.Swap(&b); }
  inline void Swap(Notification_Available* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification_Available* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification_Available* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Notification_Available>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Notification_Available& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Notification_Available& from) { Notification_Available::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Notification_Available* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "document.Notification.Available"; }

  explicit Notification_Available(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Notification_Available(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Notification_Available& from);
  Notification_Available(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Notification_Available&& from) noexcept
      : Notification_Available(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kBlobFieldNumber = 2,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const ::std::string& uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uuid();
  void set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uuid();

  public:
  // bytes blob = 2;
  void clear_blob() ;
  const ::std::string& blob() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_blob(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_blob();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_blob();
  void set_allocated_blob(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_blob() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_blob(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_blob();

  public:
  // @@protoc_insertion_point(class_scope:document.Notification.Available)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Notification_Available& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr blob_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_document_2enotifications_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Notification_Available_class_data_;
// -------------------------------------------------------------------

class Notification final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:document.Notification) */ {
 public:
  inline Notification() : Notification(nullptr) {}
  ~Notification() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Notification* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Notification));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Notification(::google::protobuf::internal::ConstantInitialized);

  inline Notification(const Notification& from) : Notification(nullptr, from) {}
  inline Notification(Notification&& from) noexcept
      : Notification(nullptr, ::std::move(from)) {}
  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification& operator=(Notification&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Notification& default_instance() {
    return *reinterpret_cast<const Notification*>(
        &_Notification_default_instance_);
  }
  enum NotificationCase {
    kUnsubscribe = 1,
    kPatch = 2,
    kRequired = 3,
    kAvailable = 4,
    NOTIFICATION_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Notification& a, Notification& b) { a.Swap(&b); }
  inline void Swap(Notification* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Notification* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Notification>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Notification& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Notification& from) { Notification::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Notification* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "document.Notification"; }

  explicit Notification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Notification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Notification& from);
  Notification(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Notification&& from) noexcept
      : Notification(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using UnsubscribeComplete = Notification_UnsubscribeComplete;
  using Patch = Notification_Patch;
  using Required = Notification_Required;
  using Available = Notification_Available;

  // accessors -------------------------------------------------------
  enum : int {
    kUnsubscribeFieldNumber = 1,
    kPatchFieldNumber = 2,
    kRequiredFieldNumber = 3,
    kAvailableFieldNumber = 4,
  };
  // .document.Notification.UnsubscribeComplete unsubscribe = 1;
  bool has_unsubscribe() const;
  private:
  bool _internal_has_unsubscribe() const;

  public:
  void clear_unsubscribe() ;
  const ::document::Notification_UnsubscribeComplete& unsubscribe() const;
  [[nodiscard]] ::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE release_unsubscribe();
  ::document::Notification_UnsubscribeComplete* PROTOBUF_NONNULL mutable_unsubscribe();
  void set_allocated_unsubscribe(::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_unsubscribe(::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE value);
  ::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE unsafe_arena_release_unsubscribe();

  private:
  const ::document::Notification_UnsubscribeComplete& _internal_unsubscribe() const;
  ::document::Notification_UnsubscribeComplete* PROTOBUF_NONNULL _internal_mutable_unsubscribe();

  public:
  // .document.Notification.Patch patch = 2;
  bool has_patch() const;
  private:
  bool _internal_has_patch() const;

  public:
  void clear_patch() ;
  const ::document::Notification_Patch& patch() const;
  [[nodiscard]] ::document::Notification_Patch* PROTOBUF_NULLABLE release_patch();
  ::document::Notification_Patch* PROTOBUF_NONNULL mutable_patch();
  void set_allocated_patch(::document::Notification_Patch* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_patch(::document::Notification_Patch* PROTOBUF_NULLABLE value);
  ::document::Notification_Patch* PROTOBUF_NULLABLE unsafe_arena_release_patch();

  private:
  const ::document::Notification_Patch& _internal_patch() const;
  ::document::Notification_Patch* PROTOBUF_NONNULL _internal_mutable_patch();

  public:
  // .document.Notification.Required required = 3;
  bool has_required() const;
  private:
  bool _internal_has_required() const;

  public:
  void clear_required() ;
  const ::document::Notification_Required& required() const;
  [[nodiscard]] ::document::Notification_Required* PROTOBUF_NULLABLE release_required();
  ::document::Notification_Required* PROTOBUF_NONNULL mutable_required();
  void set_allocated_required(::document::Notification_Required* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_required(::document::Notification_Required* PROTOBUF_NULLABLE value);
  ::document::Notification_Required* PROTOBUF_NULLABLE unsafe_arena_release_required();

  private:
  const ::document::Notification_Required& _internal_required() const;
  ::document::Notification_Required* PROTOBUF_NONNULL _internal_mutable_required();

  public:
  // .document.Notification.Available available = 4;
  bool has_available() const;
  private:
  bool _internal_has_available() const;

  public:
  void clear_available() ;
  const ::document::Notification_Available& available() const;
  [[nodiscard]] ::document::Notification_Available* PROTOBUF_NULLABLE release_available();
  ::document::Notification_Available* PROTOBUF_NONNULL mutable_available();
  void set_allocated_available(::document::Notification_Available* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_available(::document::Notification_Available* PROTOBUF_NULLABLE value);
  ::document::Notification_Available* PROTOBUF_NULLABLE unsafe_arena_release_available();

  private:
  const ::document::Notification_Available& _internal_available() const;
  ::document::Notification_Available* PROTOBUF_NONNULL _internal_mutable_available();

  public:
  void clear_notification();
  NotificationCase notification_case() const;
  // @@protoc_insertion_point(class_scope:document.Notification)
 private:
  class _Internal;
  void set_has_unsubscribe();
  void set_has_patch();
  void set_has_required();
  void set_has_available();
  inline bool has_notification() const;
  inline void clear_has_notification();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Notification& from_msg);
    union NotificationUnion {
      constexpr NotificationUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE unsubscribe_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE patch_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE required_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE available_;
    } notification_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_document_2enotifications_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Notification_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Notification_UnsubscribeComplete

// -------------------------------------------------------------------

// Notification_Patch

// string uuid = 1;
inline void Notification_Patch::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Notification_Patch::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.Patch.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Notification_Patch::set_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:document.Notification.Patch.uuid)
}
inline ::std::string* PROTOBUF_NONNULL Notification_Patch::mutable_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:document.Notification.Patch.uuid)
  return _s;
}
inline const ::std::string& Notification_Patch::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void Notification_Patch::_internal_set_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Notification_Patch::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Notification_Patch::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:document.Notification.Patch.uuid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uuid_.Set("", GetArena());
  }
  return released;
}
inline void Notification_Patch::set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:document.Notification.Patch.uuid)
}

// bytes blob = 2;
inline void Notification_Patch::clear_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blob_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Notification_Patch::blob() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.Patch.blob)
  return _internal_blob();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Notification_Patch::set_blob(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.blob_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:document.Notification.Patch.blob)
}
inline ::std::string* PROTOBUF_NONNULL Notification_Patch::mutable_blob()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:document.Notification.Patch.blob)
  return _s;
}
inline const ::std::string& Notification_Patch::_internal_blob() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blob_.Get();
}
inline void Notification_Patch::_internal_set_blob(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blob_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Notification_Patch::_internal_mutable_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.blob_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Notification_Patch::release_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:document.Notification.Patch.blob)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.blob_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.blob_.Set("", GetArena());
  }
  return released;
}
inline void Notification_Patch::set_allocated_blob(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.blob_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.blob_.IsDefault()) {
    _impl_.blob_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:document.Notification.Patch.blob)
}

// -------------------------------------------------------------------

// Notification_Required

// string uuid = 1;
inline void Notification_Required::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Notification_Required::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.Required.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Notification_Required::set_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:document.Notification.Required.uuid)
}
inline ::std::string* PROTOBUF_NONNULL Notification_Required::mutable_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:document.Notification.Required.uuid)
  return _s;
}
inline const ::std::string& Notification_Required::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void Notification_Required::_internal_set_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Notification_Required::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Notification_Required::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:document.Notification.Required.uuid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uuid_.Set("", GetArena());
  }
  return released;
}
inline void Notification_Required::set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:document.Notification.Required.uuid)
}

// -------------------------------------------------------------------

// Notification_Available

// string uuid = 1;
inline void Notification_Available::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Notification_Available::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.Available.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Notification_Available::set_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:document.Notification.Available.uuid)
}
inline ::std::string* PROTOBUF_NONNULL Notification_Available::mutable_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:document.Notification.Available.uuid)
  return _s;
}
inline const ::std::string& Notification_Available::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void Notification_Available::_internal_set_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Notification_Available::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Notification_Available::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:document.Notification.Available.uuid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uuid_.Set("", GetArena());
  }
  return released;
}
inline void Notification_Available::set_allocated_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:document.Notification.Available.uuid)
}

// bytes blob = 2;
inline void Notification_Available::clear_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blob_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Notification_Available::blob() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.Available.blob)
  return _internal_blob();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Notification_Available::set_blob(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.blob_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:document.Notification.Available.blob)
}
inline ::std::string* PROTOBUF_NONNULL Notification_Available::mutable_blob()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_blob();
  // @@protoc_insertion_point(field_mutable:document.Notification.Available.blob)
  return _s;
}
inline const ::std::string& Notification_Available::_internal_blob() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blob_.Get();
}
inline void Notification_Available::_internal_set_blob(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blob_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Notification_Available::_internal_mutable_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.blob_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Notification_Available::release_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:document.Notification.Available.blob)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.blob_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.blob_.Set("", GetArena());
  }
  return released;
}
inline void Notification_Available::set_allocated_blob(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.blob_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.blob_.IsDefault()) {
    _impl_.blob_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:document.Notification.Available.blob)
}

// -------------------------------------------------------------------

// Notification

// .document.Notification.UnsubscribeComplete unsubscribe = 1;
inline bool Notification::has_unsubscribe() const {
  return notification_case() == kUnsubscribe;
}
inline bool Notification::_internal_has_unsubscribe() const {
  return notification_case() == kUnsubscribe;
}
inline void Notification::set_has_unsubscribe() {
  _impl_._oneof_case_[0] = kUnsubscribe;
}
inline void Notification::clear_unsubscribe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (notification_case() == kUnsubscribe) {
    if (GetArena() == nullptr) {
      delete _impl_.notification_.unsubscribe_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.notification_.unsubscribe_);
    }
    clear_has_notification();
  }
}
inline ::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE Notification::release_unsubscribe() {
  // @@protoc_insertion_point(field_release:document.Notification.unsubscribe)
  if (notification_case() == kUnsubscribe) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_UnsubscribeComplete*>(_impl_.notification_.unsubscribe_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notification_.unsubscribe_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::document::Notification_UnsubscribeComplete& Notification::_internal_unsubscribe() const {
  return notification_case() == kUnsubscribe ? static_cast<const ::document::Notification_UnsubscribeComplete&>(*reinterpret_cast<::document::Notification_UnsubscribeComplete*>(_impl_.notification_.unsubscribe_))
                     : reinterpret_cast<const ::document::Notification_UnsubscribeComplete&>(::document::_Notification_UnsubscribeComplete_default_instance_);
}
inline const ::document::Notification_UnsubscribeComplete& Notification::unsubscribe() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.unsubscribe)
  return _internal_unsubscribe();
}
inline ::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE Notification::unsafe_arena_release_unsubscribe() {
  // @@protoc_insertion_point(field_unsafe_arena_release:document.Notification.unsubscribe)
  if (notification_case() == kUnsubscribe) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_UnsubscribeComplete*>(_impl_.notification_.unsubscribe_);
    _impl_.notification_.unsubscribe_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_unsubscribe(
    ::document::Notification_UnsubscribeComplete* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_notification();
  if (value) {
    set_has_unsubscribe();
    _impl_.notification_.unsubscribe_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:document.Notification.unsubscribe)
}
inline ::document::Notification_UnsubscribeComplete* PROTOBUF_NONNULL Notification::_internal_mutable_unsubscribe() {
  if (notification_case() != kUnsubscribe) {
    clear_notification();
    set_has_unsubscribe();
    _impl_.notification_.unsubscribe_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::document::Notification_UnsubscribeComplete>(GetArena()));
  }
  return reinterpret_cast<::document::Notification_UnsubscribeComplete*>(_impl_.notification_.unsubscribe_);
}
inline ::document::Notification_UnsubscribeComplete* PROTOBUF_NONNULL Notification::mutable_unsubscribe()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::document::Notification_UnsubscribeComplete* _msg = _internal_mutable_unsubscribe();
  // @@protoc_insertion_point(field_mutable:document.Notification.unsubscribe)
  return _msg;
}

// .document.Notification.Patch patch = 2;
inline bool Notification::has_patch() const {
  return notification_case() == kPatch;
}
inline bool Notification::_internal_has_patch() const {
  return notification_case() == kPatch;
}
inline void Notification::set_has_patch() {
  _impl_._oneof_case_[0] = kPatch;
}
inline void Notification::clear_patch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (notification_case() == kPatch) {
    if (GetArena() == nullptr) {
      delete _impl_.notification_.patch_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.notification_.patch_);
    }
    clear_has_notification();
  }
}
inline ::document::Notification_Patch* PROTOBUF_NULLABLE Notification::release_patch() {
  // @@protoc_insertion_point(field_release:document.Notification.patch)
  if (notification_case() == kPatch) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Patch*>(_impl_.notification_.patch_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notification_.patch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::document::Notification_Patch& Notification::_internal_patch() const {
  return notification_case() == kPatch ? static_cast<const ::document::Notification_Patch&>(*reinterpret_cast<::document::Notification_Patch*>(_impl_.notification_.patch_))
                     : reinterpret_cast<const ::document::Notification_Patch&>(::document::_Notification_Patch_default_instance_);
}
inline const ::document::Notification_Patch& Notification::patch() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.patch)
  return _internal_patch();
}
inline ::document::Notification_Patch* PROTOBUF_NULLABLE Notification::unsafe_arena_release_patch() {
  // @@protoc_insertion_point(field_unsafe_arena_release:document.Notification.patch)
  if (notification_case() == kPatch) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Patch*>(_impl_.notification_.patch_);
    _impl_.notification_.patch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_patch(
    ::document::Notification_Patch* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_notification();
  if (value) {
    set_has_patch();
    _impl_.notification_.patch_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:document.Notification.patch)
}
inline ::document::Notification_Patch* PROTOBUF_NONNULL Notification::_internal_mutable_patch() {
  if (notification_case() != kPatch) {
    clear_notification();
    set_has_patch();
    _impl_.notification_.patch_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::document::Notification_Patch>(GetArena()));
  }
  return reinterpret_cast<::document::Notification_Patch*>(_impl_.notification_.patch_);
}
inline ::document::Notification_Patch* PROTOBUF_NONNULL Notification::mutable_patch()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::document::Notification_Patch* _msg = _internal_mutable_patch();
  // @@protoc_insertion_point(field_mutable:document.Notification.patch)
  return _msg;
}

// .document.Notification.Required required = 3;
inline bool Notification::has_required() const {
  return notification_case() == kRequired;
}
inline bool Notification::_internal_has_required() const {
  return notification_case() == kRequired;
}
inline void Notification::set_has_required() {
  _impl_._oneof_case_[0] = kRequired;
}
inline void Notification::clear_required() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (notification_case() == kRequired) {
    if (GetArena() == nullptr) {
      delete _impl_.notification_.required_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.notification_.required_);
    }
    clear_has_notification();
  }
}
inline ::document::Notification_Required* PROTOBUF_NULLABLE Notification::release_required() {
  // @@protoc_insertion_point(field_release:document.Notification.required)
  if (notification_case() == kRequired) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Required*>(_impl_.notification_.required_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notification_.required_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::document::Notification_Required& Notification::_internal_required() const {
  return notification_case() == kRequired ? static_cast<const ::document::Notification_Required&>(*reinterpret_cast<::document::Notification_Required*>(_impl_.notification_.required_))
                     : reinterpret_cast<const ::document::Notification_Required&>(::document::_Notification_Required_default_instance_);
}
inline const ::document::Notification_Required& Notification::required() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.required)
  return _internal_required();
}
inline ::document::Notification_Required* PROTOBUF_NULLABLE Notification::unsafe_arena_release_required() {
  // @@protoc_insertion_point(field_unsafe_arena_release:document.Notification.required)
  if (notification_case() == kRequired) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Required*>(_impl_.notification_.required_);
    _impl_.notification_.required_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_required(
    ::document::Notification_Required* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_notification();
  if (value) {
    set_has_required();
    _impl_.notification_.required_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:document.Notification.required)
}
inline ::document::Notification_Required* PROTOBUF_NONNULL Notification::_internal_mutable_required() {
  if (notification_case() != kRequired) {
    clear_notification();
    set_has_required();
    _impl_.notification_.required_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::document::Notification_Required>(GetArena()));
  }
  return reinterpret_cast<::document::Notification_Required*>(_impl_.notification_.required_);
}
inline ::document::Notification_Required* PROTOBUF_NONNULL Notification::mutable_required()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::document::Notification_Required* _msg = _internal_mutable_required();
  // @@protoc_insertion_point(field_mutable:document.Notification.required)
  return _msg;
}

// .document.Notification.Available available = 4;
inline bool Notification::has_available() const {
  return notification_case() == kAvailable;
}
inline bool Notification::_internal_has_available() const {
  return notification_case() == kAvailable;
}
inline void Notification::set_has_available() {
  _impl_._oneof_case_[0] = kAvailable;
}
inline void Notification::clear_available() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (notification_case() == kAvailable) {
    if (GetArena() == nullptr) {
      delete _impl_.notification_.available_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.notification_.available_);
    }
    clear_has_notification();
  }
}
inline ::document::Notification_Available* PROTOBUF_NULLABLE Notification::release_available() {
  // @@protoc_insertion_point(field_release:document.Notification.available)
  if (notification_case() == kAvailable) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Available*>(_impl_.notification_.available_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.notification_.available_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::document::Notification_Available& Notification::_internal_available() const {
  return notification_case() == kAvailable ? static_cast<const ::document::Notification_Available&>(*reinterpret_cast<::document::Notification_Available*>(_impl_.notification_.available_))
                     : reinterpret_cast<const ::document::Notification_Available&>(::document::_Notification_Available_default_instance_);
}
inline const ::document::Notification_Available& Notification::available() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:document.Notification.available)
  return _internal_available();
}
inline ::document::Notification_Available* PROTOBUF_NULLABLE Notification::unsafe_arena_release_available() {
  // @@protoc_insertion_point(field_unsafe_arena_release:document.Notification.available)
  if (notification_case() == kAvailable) {
    clear_has_notification();
    auto* temp = reinterpret_cast<::document::Notification_Available*>(_impl_.notification_.available_);
    _impl_.notification_.available_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_available(
    ::document::Notification_Available* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_notification();
  if (value) {
    set_has_available();
    _impl_.notification_.available_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:document.Notification.available)
}
inline ::document::Notification_Available* PROTOBUF_NONNULL Notification::_internal_mutable_available() {
  if (notification_case() != kAvailable) {
    clear_notification();
    set_has_available();
    _impl_.notification_.available_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::document::Notification_Available>(GetArena()));
  }
  return reinterpret_cast<::document::Notification_Available*>(_impl_.notification_.available_);
}
inline ::document::Notification_Available* PROTOBUF_NONNULL Notification::mutable_available()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::document::Notification_Available* _msg = _internal_mutable_available();
  // @@protoc_insertion_point(field_mutable:document.Notification.available)
  return _msg;
}

inline bool Notification::has_notification() const {
  return notification_case() != NOTIFICATION_NOT_SET;
}
inline void Notification::clear_has_notification() {
  _impl_._oneof_case_[0] = NOTIFICATION_NOT_SET;
}
inline Notification::NotificationCase Notification::notification_case() const {
  return Notification::NotificationCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace document


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // document_2enotifications_2eproto_2epb_2eh
