// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hotKey.proto
// Protobuf C++ Version: 6.33.4

#ifndef hotKey_2eproto_2epb_2eh
#define hotKey_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "customOptions.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_hotKey_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_hotKey_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_hotKey_2eproto;
}  // extern "C"
namespace rv {
namespace data {
enum KeyCode : int;
extern const uint32_t KeyCode_internal_data_[];
class HotKey;
struct HotKeyDefaultTypeInternal;
extern HotKeyDefaultTypeInternal _HotKey_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HotKey_class_data_;
}  // namespace data
}  // namespace rv
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::rv::data::KeyCode_internal_data_>
    internal::EnumTraitsImpl::value<::rv::data::KeyCode>;
}  // namespace protobuf
}  // namespace google

namespace rv {
namespace data {
enum KeyCode : int {
  KEY_CODE_UNKNOWN = 0,
  KEY_CODE_ANSI_A = 1,
  KEY_CODE_ANSI_B = 2,
  KEY_CODE_ANSI_C = 3,
  KEY_CODE_ANSI_D = 4,
  KEY_CODE_ANSI_E = 5,
  KEY_CODE_ANSI_F = 6,
  KEY_CODE_ANSI_G = 7,
  KEY_CODE_ANSI_H = 8,
  KEY_CODE_ANSI_I = 9,
  KEY_CODE_ANSI_J = 10,
  KEY_CODE_ANSI_K = 11,
  KEY_CODE_ANSI_L = 12,
  KEY_CODE_ANSI_M = 13,
  KEY_CODE_ANSI_N = 14,
  KEY_CODE_ANSI_O = 15,
  KEY_CODE_ANSI_P = 16,
  KEY_CODE_ANSI_Q = 17,
  KEY_CODE_ANSI_R = 18,
  KEY_CODE_ANSI_S = 19,
  KEY_CODE_ANSI_T = 20,
  KEY_CODE_ANSI_U = 21,
  KEY_CODE_ANSI_V = 22,
  KEY_CODE_ANSI_W = 23,
  KEY_CODE_ANSI_X = 24,
  KEY_CODE_ANSI_Y = 25,
  KEY_CODE_ANSI_Z = 26,
  KEY_CODE_ANSI_0 = 27,
  KEY_CODE_ANSI_1 = 28,
  KEY_CODE_ANSI_2 = 29,
  KEY_CODE_ANSI_3 = 30,
  KEY_CODE_ANSI_4 = 31,
  KEY_CODE_ANSI_5 = 32,
  KEY_CODE_ANSI_6 = 33,
  KEY_CODE_ANSI_7 = 34,
  KEY_CODE_ANSI_8 = 35,
  KEY_CODE_ANSI_9 = 36,
  KEY_CODE_ANSI_EQUAL = 37,
  KEY_CODE_ANSI_MINUS = 38,
  KEY_CODE_ANSI_RIGHT_BRACKET = 39,
  KEY_CODE_ANSI_LEFT_BRACKET = 40,
  KEY_CODE_ANSI_QUOTE = 41,
  KEY_CODE_ANSI_SEMICOLON = 42,
  KEY_CODE_ANSI_BACKSLASH = 43,
  KEY_CODE_ANSI_COMMA = 44,
  KEY_CODE_ANSI_SLASH = 45,
  KEY_CODE_ANSI_PERIOD = 46,
  KEY_CODE_ANSI_GRAVE = 47,
  KEY_CODE_ANSI_KEYPAD_DECIMAL = 48,
  KEY_CODE_ANSI_KEYPAD_PLUS = 49,
  KEY_CODE_ANSI_KEYPAD_CLEAR = 50,
  KEY_CODE_ANSI_KEYPAD_DIVIDE = 51,
  KEY_CODE_ANSI_KEYPAD_ENTER = 52,
  KEY_CODE_ANSI_KEYPAD_MINUS = 53,
  KEY_CODE_ANSI_KEYPAD_EQUALS = 54,
  KEY_CODE_ANSI_KEYPAD_0 = 55,
  KEY_CODE_ANSI_KEYPAD_1 = 56,
  KEY_CODE_ANSI_KEYPAD_2 = 57,
  KEY_CODE_ANSI_KEYPAD_3 = 58,
  KEY_CODE_ANSI_KEYPAD_4 = 59,
  KEY_CODE_ANSI_KEYPAD_5 = 60,
  KEY_CODE_ANSI_KEYPAD_6 = 61,
  KEY_CODE_ANSI_KEYPAD_7 = 62,
  KEY_CODE_ANSI_KEYPAD_8 = 63,
  KEY_CODE_ANSI_KEYPAD_9 = 64,
  KEY_CODE_F1 = 65,
  KEY_CODE_F2 = 66,
  KEY_CODE_F3 = 67,
  KEY_CODE_F4 = 68,
  KEY_CODE_F5 = 69,
  KEY_CODE_F6 = 70,
  KEY_CODE_F7 = 71,
  KEY_CODE_F8 = 72,
  KEY_CODE_F9 = 73,
  KEY_CODE_F10 = 74,
  KEY_CODE_F11 = 75,
  KEY_CODE_F12 = 76,
  KEY_CODE_F13 = 77,
  KEY_CODE_F14 = 78,
  KEY_CODE_F15 = 79,
  KEY_CODE_F16 = 80,
  KEY_CODE_F17 = 81,
  KEY_CODE_F18 = 82,
  KEY_CODE_F19 = 83,
  KEY_CODE_F20 = 84,
  KEY_CODE_FUNCTION = 85,
  KEY_CODE_RETURN = 86,
  KEY_CODE_TAB = 87,
  KEY_CODE_SPACE = 88,
  KEY_CODE_DELETE = 89,
  KEY_CODE_ESCAPE = 90,
  KEY_CODE_COMMAND = 91,
  KEY_CODE_SHIFT = 92,
  KEY_CODE_CAPS_LOCK = 93,
  KEY_CODE_OPTION = 94,
  KEY_CODE_CONTROL = 95,
  KEY_CODE_RIGHT_SHIFT = 96,
  KEY_CODE_RIGHT_OPTION = 97,
  KEY_CODE_RIGHT_CONTROL = 98,
  KEY_CODE_VOLUME_UP = 99,
  KEY_CODE_VOLUME_DOWN = 100,
  KEY_CODE_MUTE = 101,
  KEY_CODE_HELP = 102,
  KEY_CODE_HOME = 103,
  KEY_CODE_PAGE_UP = 104,
  KEY_CODE_FORWARD_DELETE = 105,
  KEY_CODE_END = 106,
  KEY_CODE_PAGE_DOWN = 107,
  KEY_CODE_LEFT_ARROW = 108,
  KEY_CODE_RIGHT_ARROW = 109,
  KEY_CODE_DOWN_ARROW = 110,
  KEY_CODE_UP_ARROW = 111,
  KEY_CODE_ISO_SELECTION = 112,
  KEY_CODE_JIS_YEN = 113,
  KEY_CODE_JIS_UNDERSCORE = 114,
  KEY_CODE_JIS_KEYPAD_COMMA = 115,
  KEY_CODE_JIS_EISU = 116,
  KEY_CODE_JIS_KANA = 117,
  KeyCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  KeyCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t KeyCode_internal_data_[];
inline constexpr KeyCode KeyCode_MIN =
    static_cast<KeyCode>(0);
inline constexpr KeyCode KeyCode_MAX =
    static_cast<KeyCode>(117);
inline bool KeyCode_IsValid(int value) {
  return 0 <= value && value <= 117;
}
inline constexpr int KeyCode_ARRAYSIZE = 117 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL KeyCode_descriptor();
template <typename T>
const ::std::string& KeyCode_Name(T value) {
  static_assert(::std::is_same<T, KeyCode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to KeyCode_Name().");
  return KeyCode_Name(static_cast<KeyCode>(value));
}
template <>
inline const ::std::string& KeyCode_Name(KeyCode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<KeyCode_descriptor, 0, 117>(
      static_cast<int>(value));
}
inline bool KeyCode_Parse(
    ::absl::string_view name, KeyCode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<KeyCode>(KeyCode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class HotKey final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:rv.data.HotKey) */ {
 public:
  inline HotKey() : HotKey(nullptr) {}
  ~HotKey() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HotKey* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HotKey));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HotKey(::google::protobuf::internal::ConstantInitialized);

  inline HotKey(const HotKey& from) : HotKey(nullptr, from) {}
  inline HotKey(HotKey&& from) noexcept
      : HotKey(nullptr, ::std::move(from)) {}
  inline HotKey& operator=(const HotKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline HotKey& operator=(HotKey&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HotKey& default_instance() {
    return *reinterpret_cast<const HotKey*>(
        &_HotKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HotKey& a, HotKey& b) { a.Swap(&b); }
  inline void Swap(HotKey* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HotKey* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HotKey* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HotKey>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HotKey& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HotKey& from) { HotKey::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HotKey* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "rv.data.HotKey"; }

  explicit HotKey(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HotKey(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HotKey& from);
  HotKey(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HotKey&& from) noexcept
      : HotKey(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kControlIdentifierFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string control_identifier = 2;
  void clear_control_identifier() ;
  const ::std::string& control_identifier() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_control_identifier(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_control_identifier();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_control_identifier();
  void set_allocated_control_identifier(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_control_identifier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_control_identifier(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_control_identifier();

  public:
  // .rv.data.KeyCode code = 1;
  void clear_code() ;
  ::rv::data::KeyCode code() const;
  void set_code(::rv::data::KeyCode value);

  private:
  ::rv::data::KeyCode _internal_code() const;
  void _internal_set_code(::rv::data::KeyCode value);

  public:
  // @@protoc_insertion_point(class_scope:rv.data.HotKey)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HotKey& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr control_identifier_;
    int code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hotKey_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HotKey_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HotKey

// .rv.data.KeyCode code = 1;
inline void HotKey::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::rv::data::KeyCode HotKey::code() const {
  // @@protoc_insertion_point(field_get:rv.data.HotKey.code)
  return _internal_code();
}
inline void HotKey::set_code(::rv::data::KeyCode value) {
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:rv.data.HotKey.code)
}
inline ::rv::data::KeyCode HotKey::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::rv::data::KeyCode>(_impl_.code_);
}
inline void HotKey::_internal_set_code(::rv::data::KeyCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string control_identifier = 2;
inline void HotKey::clear_control_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.control_identifier_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HotKey::control_identifier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:rv.data.HotKey.control_identifier)
  return _internal_control_identifier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HotKey::set_control_identifier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.control_identifier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:rv.data.HotKey.control_identifier)
}
inline ::std::string* PROTOBUF_NONNULL HotKey::mutable_control_identifier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_control_identifier();
  // @@protoc_insertion_point(field_mutable:rv.data.HotKey.control_identifier)
  return _s;
}
inline const ::std::string& HotKey::_internal_control_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.control_identifier_.Get();
}
inline void HotKey::_internal_set_control_identifier(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.control_identifier_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HotKey::_internal_mutable_control_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.control_identifier_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HotKey::release_control_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:rv.data.HotKey.control_identifier)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.control_identifier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.control_identifier_.Set("", GetArena());
  }
  return released;
}
inline void HotKey::set_allocated_control_identifier(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.control_identifier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.control_identifier_.IsDefault()) {
    _impl_.control_identifier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:rv.data.HotKey.control_identifier)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace rv


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::rv::data::KeyCode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::rv::data::KeyCode>() {
  return ::rv::data::KeyCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // hotKey_2eproto_2epb_2eh
