// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: params.proto
// Protobuf C++ Version: 6.33.4

#include "params.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace application {

inline constexpr Shutdown::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Shutdown::Shutdown(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Shutdown_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ShutdownDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShutdownDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShutdownDefaultTypeInternal() {}
  union {
    Shutdown _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShutdownDefaultTypeInternal _Shutdown_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR RegistrationCreationOption::RegistrationCreationOption(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(RegistrationCreationOption_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RegistrationCreationOptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegistrationCreationOptionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegistrationCreationOptionDefaultTypeInternal() {}
  union {
    RegistrationCreationOption _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegistrationCreationOptionDefaultTypeInternal _RegistrationCreationOption_default_instance_;

inline constexpr ProductInformation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        product_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        major_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        minor_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        patch_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        build_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        build_date_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR ProductInformation::ProductInformation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProductInformation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProductInformationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProductInformationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProductInformationDefaultTypeInternal() {}
  union {
    ProductInformation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProductInformationDefaultTypeInternal _ProductInformation_default_instance_;

inline constexpr ApplicationParams::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        enabled_features_{},
        product_info_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ApplicationParams::ApplicationParams(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ApplicationParams_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ApplicationParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ApplicationParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ApplicationParamsDefaultTypeInternal() {}
  union {
    ApplicationParams _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApplicationParamsDefaultTypeInternal _ApplicationParams_default_instance_;

inline constexpr ApplicationStartParams::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        application_{nullptr},
        media_v1_{nullptr},
        media_{nullptr},
        feature_flags_{nullptr},
        collaboration_poc_{nullptr},
        registration_{nullptr},
        document_{nullptr},
        workspace_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ApplicationStartParams::ApplicationStartParams(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ApplicationStartParams_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ApplicationStartParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ApplicationStartParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ApplicationStartParamsDefaultTypeInternal() {}
  union {
    ApplicationStartParams _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApplicationStartParamsDefaultTypeInternal _ApplicationStartParams_default_instance_;
}  // namespace application
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_params_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_params_2eproto = nullptr;
const ::uint32_t
    TableStruct_params_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.product_name_),
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.major_version_),
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.minor_version_),
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.patch_version_),
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.build_number_),
        PROTOBUF_FIELD_OFFSET(::application::ProductInformation, _impl_.build_date_),
        0,
        1,
        2,
        3,
        4,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::application::ApplicationParams, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::application::ApplicationParams, _impl_.product_info_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationParams, _impl_.enabled_features_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.application_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.media_v1_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.media_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.feature_flags_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.collaboration_poc_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.registration_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.document_),
        PROTOBUF_FIELD_OFFSET(::application::ApplicationStartParams, _impl_.workspace_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        0x000, // bitmap
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::application::Shutdown, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::application::Shutdown, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::application::Shutdown, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::application::Shutdown, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::application::ProductInformation)},
        {15, sizeof(::application::ApplicationParams)},
        {22, sizeof(::application::ApplicationStartParams)},
        {41, sizeof(::application::RegistrationCreationOption)},
        {42, sizeof(::application::Shutdown)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::application::_ProductInformation_default_instance_._instance,
    &::application::_ApplicationParams_default_instance_._instance,
    &::application::_ApplicationStartParams_default_instance_._instance,
    &::application::_RegistrationCreationOption_default_instance_._instance,
    &::application::_Shutdown_default_instance_._instance,
};
const char descriptor_table_protodef_params_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014params.proto\022\013application\032\026v1-helper-c"
    "ommon.proto\032\026v2-helper-common.proto\032\023fea"
    "ture-flags.proto\032\027collaboration-poc.prot"
    "o\032\030document.bootstrap.proto\032\031workspace.b"
    "ootstrap.proto\"\231\001\n\022ProductInformation\022\024\n"
    "\014product_name\030\001 \001(\t\022\025\n\rmajor_version\030\002 \001"
    "(\t\022\025\n\rminor_version\030\003 \001(\t\022\025\n\rpatch_versi"
    "on\030\004 \001(\t\022\024\n\014build_number\030\005 \001(\t\022\022\n\nbuild_"
    "date\030\006 \001(\003\"d\n\021ApplicationParams\0225\n\014produ"
    "ct_info\030\001 \001(\0132\037.application.ProductInfor"
    "mation\022\030\n\020enabled_features\030\002 \003(\t\"\277\003\n\026App"
    "licationStartParams\0223\n\013application\030\001 \001(\013"
    "2\036.application.ApplicationParams\0222\n\010medi"
    "a_v1\030\002 \001(\0132 .helper.common.v1.CreationOp"
    "tion\022/\n\005media\030\003 \001(\0132 .helper.common.v2.C"
    "reationOption\0224\n\rfeature_flags\030\004 \001(\0132\035.f"
    "eature_flags.CreationOption\022<\n\021collabora"
    "tion_poc\030\005 \001(\0132!.collaboration_poc.Creat"
    "ionOption\022=\n\014registration\030\006 \001(\0132\'.applic"
    "ation.RegistrationCreationOption\022*\n\010docu"
    "ment\030\007 \001(\0132\030.document.CreationOption\022,\n\t"
    "workspace\030\010 \001(\0132\031.workspace.CreationOpti"
    "on\"\034\n\032RegistrationCreationOption\"3\n\010Shut"
    "down\022\014\n\002ok\030\001 \001(\tH\000\022\017\n\005error\030\002 \001(\tH\000B\010\n\006r"
    "esultb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_params_2eproto_deps[6] = {
        &::descriptor_table_collaboration_2dpoc_2eproto,
        &::descriptor_table_document_2ebootstrap_2eproto,
        &::descriptor_table_feature_2dflags_2eproto,
        &::descriptor_table_v1_2dhelper_2dcommon_2eproto,
        &::descriptor_table_v2_2dhelper_2dcommon_2eproto,
        &::descriptor_table_workspace_2ebootstrap_2eproto,
};
static ::absl::once_flag descriptor_table_params_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_params_2eproto = {
    false,
    false,
    973,
    descriptor_table_protodef_params_2eproto,
    "params.proto",
    &descriptor_table_params_2eproto_once,
    descriptor_table_params_2eproto_deps,
    6,
    5,
    schemas,
    file_default_instances,
    TableStruct_params_2eproto::offsets,
    file_level_enum_descriptors_params_2eproto,
    file_level_service_descriptors_params_2eproto,
};
namespace application {
// ===================================================================

class ProductInformation::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ProductInformation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_._has_bits_);
};

ProductInformation::ProductInformation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProductInformation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:application.ProductInformation)
}
PROTOBUF_NDEBUG_INLINE ProductInformation::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::application::ProductInformation& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        product_name_(arena, from.product_name_),
        major_version_(arena, from.major_version_),
        minor_version_(arena, from.minor_version_),
        patch_version_(arena, from.patch_version_),
        build_number_(arena, from.build_number_) {}

ProductInformation::ProductInformation(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProductInformation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProductInformation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProductInformation* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.build_date_ = from._impl_.build_date_;

  // @@protoc_insertion_point(copy_constructor:application.ProductInformation)
}
PROTOBUF_NDEBUG_INLINE ProductInformation::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        product_name_(arena),
        major_version_(arena),
        minor_version_(arena),
        patch_version_(arena),
        build_number_(arena) {}

inline void ProductInformation::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.build_date_ = {};
}
ProductInformation::~ProductInformation() {
  // @@protoc_insertion_point(destructor:application.ProductInformation)
  SharedDtor(*this);
}
inline void ProductInformation::SharedDtor(MessageLite& self) {
  ProductInformation& this_ = static_cast<ProductInformation&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.product_name_.Destroy();
  this_._impl_.major_version_.Destroy();
  this_._impl_.minor_version_.Destroy();
  this_._impl_.patch_version_.Destroy();
  this_._impl_.build_number_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProductInformation::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProductInformation(arena);
}
constexpr auto ProductInformation::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ProductInformation),
                                            alignof(ProductInformation));
}
constexpr auto ProductInformation::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProductInformation_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProductInformation::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProductInformation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProductInformation::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProductInformation>(), &ProductInformation::ByteSizeLong,
              &ProductInformation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_._cached_size_),
          false,
      },
      &ProductInformation::kDescriptorMethods,
      &descriptor_table_params_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProductInformation_class_data_ =
        ProductInformation::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ProductInformation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProductInformation_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProductInformation_class_data_.tc_table);
  return ProductInformation_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 102, 2>
ProductInformation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ProductInformation_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::application::ProductInformation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string product_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.product_name_)}},
    // string major_version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.major_version_)}},
    // string minor_version = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.minor_version_)}},
    // string patch_version = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.patch_version_)}},
    // string build_number = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 4, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.build_number_)}},
    // int64 build_date = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProductInformation, _impl_.build_date_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.build_date_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string product_name = 1;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.product_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string major_version = 2;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.major_version_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string minor_version = 3;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.minor_version_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string patch_version = 4;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.patch_version_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string build_number = 5;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.build_number_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 build_date = 6;
    {PROTOBUF_FIELD_OFFSET(ProductInformation, _impl_.build_date_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\36\14\15\15\15\14\0\0"
    "application.ProductInformation"
    "product_name"
    "major_version"
    "minor_version"
    "patch_version"
    "build_number"
  }},
};
PROTOBUF_NOINLINE void ProductInformation::Clear() {
// @@protoc_insertion_point(message_clear_start:application.ProductInformation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.product_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.major_version_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.minor_version_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.patch_version_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.build_number_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.build_date_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProductInformation::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProductInformation& this_ = static_cast<const ProductInformation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProductInformation::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProductInformation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:application.ProductInformation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string product_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_product_name().empty()) {
      const ::std::string& _s = this_._internal_product_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ProductInformation.product_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string major_version = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_major_version().empty()) {
      const ::std::string& _s = this_._internal_major_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ProductInformation.major_version");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string minor_version = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_minor_version().empty()) {
      const ::std::string& _s = this_._internal_minor_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ProductInformation.minor_version");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string patch_version = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_patch_version().empty()) {
      const ::std::string& _s = this_._internal_patch_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ProductInformation.patch_version");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string build_number = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_build_number().empty()) {
      const ::std::string& _s = this_._internal_build_number();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ProductInformation.build_number");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // int64 build_date = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_build_date() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
              stream, this_._internal_build_date(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:application.ProductInformation)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProductInformation::ByteSizeLong(const MessageLite& base) {
  const ProductInformation& this_ = static_cast<const ProductInformation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProductInformation::ByteSizeLong() const {
  const ProductInformation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:application.ProductInformation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string product_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_product_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_product_name());
      }
    }
    // string major_version = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_major_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_major_version());
      }
    }
    // string minor_version = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_minor_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_minor_version());
      }
    }
    // string patch_version = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_patch_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_patch_version());
      }
    }
    // string build_number = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_build_number().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_build_number());
      }
    }
    // int64 build_date = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_build_date() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_build_date());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProductInformation::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ProductInformation*>(&to_msg);
  auto& from = static_cast<const ProductInformation&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:application.ProductInformation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_product_name().empty()) {
        _this->_internal_set_product_name(from._internal_product_name());
      } else {
        if (_this->_impl_.product_name_.IsDefault()) {
          _this->_internal_set_product_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_major_version().empty()) {
        _this->_internal_set_major_version(from._internal_major_version());
      } else {
        if (_this->_impl_.major_version_.IsDefault()) {
          _this->_internal_set_major_version("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_minor_version().empty()) {
        _this->_internal_set_minor_version(from._internal_minor_version());
      } else {
        if (_this->_impl_.minor_version_.IsDefault()) {
          _this->_internal_set_minor_version("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_patch_version().empty()) {
        _this->_internal_set_patch_version(from._internal_patch_version());
      } else {
        if (_this->_impl_.patch_version_.IsDefault()) {
          _this->_internal_set_patch_version("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_build_number().empty()) {
        _this->_internal_set_build_number(from._internal_build_number());
      } else {
        if (_this->_impl_.build_number_.IsDefault()) {
          _this->_internal_set_build_number("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_build_date() != 0) {
        _this->_impl_.build_date_ = from._impl_.build_date_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ProductInformation::CopyFrom(const ProductInformation& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:application.ProductInformation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProductInformation::InternalSwap(ProductInformation* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.product_name_, &other->_impl_.product_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.major_version_, &other->_impl_.major_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.minor_version_, &other->_impl_.minor_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.patch_version_, &other->_impl_.patch_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.build_number_, &other->_impl_.build_number_, arena);
  swap(_impl_.build_date_, other->_impl_.build_date_);
}

::google::protobuf::Metadata ProductInformation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ApplicationParams::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ApplicationParams>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_._has_bits_);
};

ApplicationParams::ApplicationParams(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ApplicationParams_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:application.ApplicationParams)
}
PROTOBUF_NDEBUG_INLINE ApplicationParams::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::application::ApplicationParams& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        enabled_features_{visibility, arena, from.enabled_features_} {}

ApplicationParams::ApplicationParams(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ApplicationParams& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ApplicationParams_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ApplicationParams* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.product_info_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.product_info_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:application.ApplicationParams)
}
PROTOBUF_NDEBUG_INLINE ApplicationParams::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        enabled_features_{visibility, arena} {}

inline void ApplicationParams::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.product_info_ = {};
}
ApplicationParams::~ApplicationParams() {
  // @@protoc_insertion_point(destructor:application.ApplicationParams)
  SharedDtor(*this);
}
inline void ApplicationParams::SharedDtor(MessageLite& self) {
  ApplicationParams& this_ = static_cast<ApplicationParams&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.product_info_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ApplicationParams::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ApplicationParams(arena);
}
constexpr auto ApplicationParams::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_.enabled_features_) +
          decltype(ApplicationParams::_impl_.enabled_features_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ApplicationParams), alignof(ApplicationParams), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ApplicationParams::PlacementNew_,
                                 sizeof(ApplicationParams),
                                 alignof(ApplicationParams));
  }
}
constexpr auto ApplicationParams::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ApplicationParams_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ApplicationParams::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ApplicationParams>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ApplicationParams::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ApplicationParams>(), &ApplicationParams::ByteSizeLong,
              &ApplicationParams::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_._cached_size_),
          false,
      },
      &ApplicationParams::kDescriptorMethods,
      &descriptor_table_params_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ApplicationParams_class_data_ =
        ApplicationParams::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ApplicationParams::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ApplicationParams_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ApplicationParams_class_data_.tc_table);
  return ApplicationParams_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 54, 2>
ApplicationParams::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ApplicationParams_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::application::ApplicationParams>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string enabled_features = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_.enabled_features_)}},
    // .application.ProductInformation product_info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_.product_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .application.ProductInformation product_info = 1;
    {PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_.product_info_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string enabled_features = 2;
    {PROTOBUF_FIELD_OFFSET(ApplicationParams, _impl_.enabled_features_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::application::ProductInformation>()},
  }},
  {{
    "\35\0\20\0\0\0\0\0"
    "application.ApplicationParams"
    "enabled_features"
  }},
};
PROTOBUF_NOINLINE void ApplicationParams::Clear() {
// @@protoc_insertion_point(message_clear_start:application.ApplicationParams)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.enabled_features_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.product_info_ != nullptr);
      _impl_.product_info_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ApplicationParams::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ApplicationParams& this_ = static_cast<const ApplicationParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ApplicationParams::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ApplicationParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:application.ApplicationParams)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .application.ProductInformation product_info = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.product_info_, this_._impl_.product_info_->GetCachedSize(), target,
        stream);
  }

  // repeated string enabled_features = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_enabled_features_size(); i < n; ++i) {
      const auto& s = this_._internal_enabled_features().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.ApplicationParams.enabled_features");
      target = stream->WriteString(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:application.ApplicationParams)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ApplicationParams::ByteSizeLong(const MessageLite& base) {
  const ApplicationParams& this_ = static_cast<const ApplicationParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ApplicationParams::ByteSizeLong() const {
  const ApplicationParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:application.ApplicationParams)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated string enabled_features = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_enabled_features().size());
      for (int i = 0, n = this_._internal_enabled_features().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_enabled_features().Get(i));
      }
    }
    // .application.ProductInformation product_info = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.product_info_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ApplicationParams::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ApplicationParams*>(&to_msg);
  auto& from = static_cast<const ApplicationParams&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:application.ApplicationParams)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_enabled_features()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_enabled_features());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.product_info_ != nullptr);
      if (_this->_impl_.product_info_ == nullptr) {
        _this->_impl_.product_info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.product_info_);
      } else {
        _this->_impl_.product_info_->MergeFrom(*from._impl_.product_info_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ApplicationParams::CopyFrom(const ApplicationParams& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:application.ApplicationParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ApplicationParams::InternalSwap(ApplicationParams* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.enabled_features_.InternalSwap(&other->_impl_.enabled_features_);
  swap(_impl_.product_info_, other->_impl_.product_info_);
}

::google::protobuf::Metadata ApplicationParams::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ApplicationStartParams::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ApplicationStartParams>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_._has_bits_);
};

void ApplicationStartParams::clear_media_v1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.media_v1_ != nullptr) _impl_.media_v1_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void ApplicationStartParams::clear_media() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.media_ != nullptr) _impl_.media_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
void ApplicationStartParams::clear_feature_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.feature_flags_ != nullptr) _impl_.feature_flags_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
void ApplicationStartParams::clear_collaboration_poc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.collaboration_poc_ != nullptr) _impl_.collaboration_poc_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
void ApplicationStartParams::clear_document() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.document_ != nullptr) _impl_.document_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
void ApplicationStartParams::clear_workspace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.workspace_ != nullptr) _impl_.workspace_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
ApplicationStartParams::ApplicationStartParams(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ApplicationStartParams_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:application.ApplicationStartParams)
}
PROTOBUF_NDEBUG_INLINE ApplicationStartParams::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::application::ApplicationStartParams& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ApplicationStartParams::ApplicationStartParams(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ApplicationStartParams& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ApplicationStartParams_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ApplicationStartParams* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.application_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.application_)
                : nullptr;
  _impl_.media_v1_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_v1_)
                : nullptr;
  _impl_.media_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_)
                : nullptr;
  _impl_.feature_flags_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.feature_flags_)
                : nullptr;
  _impl_.collaboration_poc_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.collaboration_poc_)
                : nullptr;
  _impl_.registration_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.registration_)
                : nullptr;
  _impl_.document_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.document_)
                : nullptr;
  _impl_.workspace_ = (CheckHasBit(cached_has_bits, 0x00000080U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.workspace_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:application.ApplicationStartParams)
}
PROTOBUF_NDEBUG_INLINE ApplicationStartParams::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ApplicationStartParams::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, application_),
           0,
           offsetof(Impl_, workspace_) -
               offsetof(Impl_, application_) +
               sizeof(Impl_::workspace_));
}
ApplicationStartParams::~ApplicationStartParams() {
  // @@protoc_insertion_point(destructor:application.ApplicationStartParams)
  SharedDtor(*this);
}
inline void ApplicationStartParams::SharedDtor(MessageLite& self) {
  ApplicationStartParams& this_ = static_cast<ApplicationStartParams&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.application_;
  delete this_._impl_.media_v1_;
  delete this_._impl_.media_;
  delete this_._impl_.feature_flags_;
  delete this_._impl_.collaboration_poc_;
  delete this_._impl_.registration_;
  delete this_._impl_.document_;
  delete this_._impl_.workspace_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ApplicationStartParams::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ApplicationStartParams(arena);
}
constexpr auto ApplicationStartParams::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ApplicationStartParams),
                                            alignof(ApplicationStartParams));
}
constexpr auto ApplicationStartParams::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ApplicationStartParams_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ApplicationStartParams::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ApplicationStartParams>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ApplicationStartParams::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ApplicationStartParams>(), &ApplicationStartParams::ByteSizeLong,
              &ApplicationStartParams::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_._cached_size_),
          false,
      },
      &ApplicationStartParams::kDescriptorMethods,
      &descriptor_table_params_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ApplicationStartParams_class_data_ =
        ApplicationStartParams::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ApplicationStartParams::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ApplicationStartParams_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ApplicationStartParams_class_data_.tc_table);
  return ApplicationStartParams_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 8, 0, 2>
ApplicationStartParams::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    8,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ApplicationStartParams_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::application::ApplicationStartParams>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .workspace.CreationOption workspace = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 7, 7,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.workspace_)}},
    // .application.ApplicationParams application = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.application_)}},
    // .helper.common.v1.CreationOption media_v1 = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.media_v1_)}},
    // .helper.common.v2.CreationOption media = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.media_)}},
    // .feature_flags.CreationOption feature_flags = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.feature_flags_)}},
    // .collaboration_poc.CreationOption collaboration_poc = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.collaboration_poc_)}},
    // .application.RegistrationCreationOption registration = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 5, 5,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.registration_)}},
    // .document.CreationOption document = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 6, 6,
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.document_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .application.ApplicationParams application = 1;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.application_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .helper.common.v1.CreationOption media_v1 = 2;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.media_v1_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .helper.common.v2.CreationOption media = 3;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.media_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .feature_flags.CreationOption feature_flags = 4;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.feature_flags_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .collaboration_poc.CreationOption collaboration_poc = 5;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.collaboration_poc_), _Internal::kHasBitsOffset + 4, 4, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .application.RegistrationCreationOption registration = 6;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.registration_), _Internal::kHasBitsOffset + 5, 5, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .document.CreationOption document = 7;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.document_), _Internal::kHasBitsOffset + 6, 6, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .workspace.CreationOption workspace = 8;
    {PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.workspace_), _Internal::kHasBitsOffset + 7, 7, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::application::ApplicationParams>()},
      {::_pbi::TcParser::GetTable<::helper::common::v1::CreationOption>()},
      {::_pbi::TcParser::GetTable<::helper::common::v2::CreationOption>()},
      {::_pbi::TcParser::GetTable<::feature_flags::CreationOption>()},
      {::_pbi::TcParser::GetTable<::collaboration_poc::CreationOption>()},
      {::_pbi::TcParser::GetTable<::application::RegistrationCreationOption>()},
      {::_pbi::TcParser::GetTable<::document::CreationOption>()},
      {::_pbi::TcParser::GetTable<::workspace::CreationOption>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ApplicationStartParams::Clear() {
// @@protoc_insertion_point(message_clear_start:application.ApplicationStartParams)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.application_ != nullptr);
      _impl_.application_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.media_v1_ != nullptr);
      _impl_.media_v1_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.media_ != nullptr);
      _impl_.media_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.feature_flags_ != nullptr);
      _impl_.feature_flags_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.collaboration_poc_ != nullptr);
      _impl_.collaboration_poc_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.registration_ != nullptr);
      _impl_.registration_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.document_ != nullptr);
      _impl_.document_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(_impl_.workspace_ != nullptr);
      _impl_.workspace_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ApplicationStartParams::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ApplicationStartParams& this_ = static_cast<const ApplicationStartParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ApplicationStartParams::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ApplicationStartParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:application.ApplicationStartParams)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .application.ApplicationParams application = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.application_, this_._impl_.application_->GetCachedSize(), target,
        stream);
  }

  // .helper.common.v1.CreationOption media_v1 = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.media_v1_, this_._impl_.media_v1_->GetCachedSize(), target,
        stream);
  }

  // .helper.common.v2.CreationOption media = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.media_, this_._impl_.media_->GetCachedSize(), target,
        stream);
  }

  // .feature_flags.CreationOption feature_flags = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.feature_flags_, this_._impl_.feature_flags_->GetCachedSize(), target,
        stream);
  }

  // .collaboration_poc.CreationOption collaboration_poc = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.collaboration_poc_, this_._impl_.collaboration_poc_->GetCachedSize(), target,
        stream);
  }

  // .application.RegistrationCreationOption registration = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.registration_, this_._impl_.registration_->GetCachedSize(), target,
        stream);
  }

  // .document.CreationOption document = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.document_, this_._impl_.document_->GetCachedSize(), target,
        stream);
  }

  // .workspace.CreationOption workspace = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.workspace_, this_._impl_.workspace_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:application.ApplicationStartParams)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ApplicationStartParams::ByteSizeLong(const MessageLite& base) {
  const ApplicationStartParams& this_ = static_cast<const ApplicationStartParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ApplicationStartParams::ByteSizeLong() const {
  const ApplicationStartParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:application.ApplicationStartParams)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // .application.ApplicationParams application = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.application_);
    }
    // .helper.common.v1.CreationOption media_v1 = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.media_v1_);
    }
    // .helper.common.v2.CreationOption media = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.media_);
    }
    // .feature_flags.CreationOption feature_flags = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.feature_flags_);
    }
    // .collaboration_poc.CreationOption collaboration_poc = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.collaboration_poc_);
    }
    // .application.RegistrationCreationOption registration = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.registration_);
    }
    // .document.CreationOption document = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.document_);
    }
    // .workspace.CreationOption workspace = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.workspace_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ApplicationStartParams::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ApplicationStartParams*>(&to_msg);
  auto& from = static_cast<const ApplicationStartParams&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:application.ApplicationStartParams)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.application_ != nullptr);
      if (_this->_impl_.application_ == nullptr) {
        _this->_impl_.application_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.application_);
      } else {
        _this->_impl_.application_->MergeFrom(*from._impl_.application_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.media_v1_ != nullptr);
      if (_this->_impl_.media_v1_ == nullptr) {
        _this->_impl_.media_v1_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_v1_);
      } else {
        _this->_impl_.media_v1_->MergeFrom(*from._impl_.media_v1_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.media_ != nullptr);
      if (_this->_impl_.media_ == nullptr) {
        _this->_impl_.media_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_);
      } else {
        _this->_impl_.media_->MergeFrom(*from._impl_.media_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.feature_flags_ != nullptr);
      if (_this->_impl_.feature_flags_ == nullptr) {
        _this->_impl_.feature_flags_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.feature_flags_);
      } else {
        _this->_impl_.feature_flags_->MergeFrom(*from._impl_.feature_flags_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.collaboration_poc_ != nullptr);
      if (_this->_impl_.collaboration_poc_ == nullptr) {
        _this->_impl_.collaboration_poc_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.collaboration_poc_);
      } else {
        _this->_impl_.collaboration_poc_->MergeFrom(*from._impl_.collaboration_poc_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.registration_ != nullptr);
      if (_this->_impl_.registration_ == nullptr) {
        _this->_impl_.registration_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.registration_);
      } else {
        _this->_impl_.registration_->MergeFrom(*from._impl_.registration_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.document_ != nullptr);
      if (_this->_impl_.document_ == nullptr) {
        _this->_impl_.document_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.document_);
      } else {
        _this->_impl_.document_->MergeFrom(*from._impl_.document_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(from._impl_.workspace_ != nullptr);
      if (_this->_impl_.workspace_ == nullptr) {
        _this->_impl_.workspace_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.workspace_);
      } else {
        _this->_impl_.workspace_->MergeFrom(*from._impl_.workspace_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ApplicationStartParams::CopyFrom(const ApplicationStartParams& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:application.ApplicationStartParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ApplicationStartParams::InternalSwap(ApplicationStartParams* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.workspace_)
      + sizeof(ApplicationStartParams::_impl_.workspace_)
      - PROTOBUF_FIELD_OFFSET(ApplicationStartParams, _impl_.application_)>(
          reinterpret_cast<char*>(&_impl_.application_),
          reinterpret_cast<char*>(&other->_impl_.application_));
}

::google::protobuf::Metadata ApplicationStartParams::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RegistrationCreationOption::_Internal {
 public:
};

RegistrationCreationOption::RegistrationCreationOption(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RegistrationCreationOption_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:application.RegistrationCreationOption)
}
RegistrationCreationOption::RegistrationCreationOption(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RegistrationCreationOption& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RegistrationCreationOption_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RegistrationCreationOption* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:application.RegistrationCreationOption)
}

inline void* PROTOBUF_NONNULL RegistrationCreationOption::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RegistrationCreationOption(arena);
}
constexpr auto RegistrationCreationOption::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RegistrationCreationOption),
                                            alignof(RegistrationCreationOption));
}
constexpr auto RegistrationCreationOption::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RegistrationCreationOption_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RegistrationCreationOption::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RegistrationCreationOption>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RegistrationCreationOption::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RegistrationCreationOption>(), &RegistrationCreationOption::ByteSizeLong,
              &RegistrationCreationOption::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RegistrationCreationOption, _impl_._cached_size_),
          false,
      },
      &RegistrationCreationOption::kDescriptorMethods,
      &descriptor_table_params_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RegistrationCreationOption_class_data_ =
        RegistrationCreationOption::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RegistrationCreationOption::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RegistrationCreationOption_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RegistrationCreationOption_class_data_.tc_table);
  return RegistrationCreationOption_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
RegistrationCreationOption::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RegistrationCreationOption_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::application::RegistrationCreationOption>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata RegistrationCreationOption::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Shutdown::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::application::Shutdown, _impl_._oneof_case_);
};

Shutdown::Shutdown(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Shutdown_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:application.Shutdown)
}
PROTOBUF_NDEBUG_INLINE Shutdown::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::application::Shutdown& from_msg)
      : result_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Shutdown::Shutdown(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Shutdown& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Shutdown_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Shutdown* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (result_case()) {
    case RESULT_NOT_SET:
      break;
      case kOk:
        new (&_impl_.result_.ok_) decltype(_impl_.result_.ok_){arena, from._impl_.result_.ok_};
        break;
      case kError:
        new (&_impl_.result_.error_) decltype(_impl_.result_.error_){arena, from._impl_.result_.error_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:application.Shutdown)
}
PROTOBUF_NDEBUG_INLINE Shutdown::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : result_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Shutdown::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Shutdown::~Shutdown() {
  // @@protoc_insertion_point(destructor:application.Shutdown)
  SharedDtor(*this);
}
inline void Shutdown::SharedDtor(MessageLite& self) {
  Shutdown& this_ = static_cast<Shutdown&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_result()) {
    this_.clear_result();
  }
  this_._impl_.~Impl_();
}

void Shutdown::clear_result() {
// @@protoc_insertion_point(one_of_clear_start:application.Shutdown)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (result_case()) {
    case kOk: {
      _impl_.result_.ok_.Destroy();
      break;
    }
    case kError: {
      _impl_.result_.error_.Destroy();
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESULT_NOT_SET;
}


inline void* PROTOBUF_NONNULL Shutdown::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Shutdown(arena);
}
constexpr auto Shutdown::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Shutdown),
                                            alignof(Shutdown));
}
constexpr auto Shutdown::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Shutdown_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Shutdown::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Shutdown>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Shutdown::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Shutdown>(), &Shutdown::ByteSizeLong,
              &Shutdown::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Shutdown, _impl_._cached_size_),
          false,
      },
      &Shutdown::kDescriptorMethods,
      &descriptor_table_params_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Shutdown_class_data_ =
        Shutdown::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Shutdown::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Shutdown_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Shutdown_class_data_.tc_table);
  return Shutdown_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 0, 36, 2>
Shutdown::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Shutdown_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::application::Shutdown>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string ok = 1;
    {PROTOBUF_FIELD_OFFSET(Shutdown, _impl_.result_.ok_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string error = 2;
    {PROTOBUF_FIELD_OFFSET(Shutdown, _impl_.result_.error_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\2\5\0\0\0\0\0"
    "application.Shutdown"
    "ok"
    "error"
  }},
};
PROTOBUF_NOINLINE void Shutdown::Clear() {
// @@protoc_insertion_point(message_clear_start:application.Shutdown)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_result();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Shutdown::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Shutdown& this_ = static_cast<const Shutdown&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Shutdown::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Shutdown& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:application.Shutdown)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.result_case()) {
    case kOk: {
      const ::std::string& _s = this_._internal_ok();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.Shutdown.ok");
      target = stream->WriteStringMaybeAliased(1, _s, target);
      break;
    }
    case kError: {
      const ::std::string& _s = this_._internal_error();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "application.Shutdown.error");
      target = stream->WriteStringMaybeAliased(2, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:application.Shutdown)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Shutdown::ByteSizeLong(const MessageLite& base) {
  const Shutdown& this_ = static_cast<const Shutdown&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Shutdown::ByteSizeLong() const {
  const Shutdown& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:application.Shutdown)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.result_case()) {
    // string ok = 1;
    case kOk: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_ok());
      break;
    }
    // string error = 2;
    case kError: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_error());
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Shutdown::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Shutdown*>(&to_msg);
  auto& from = static_cast<const Shutdown&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:application.Shutdown)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_result();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kOk: {
        if (oneof_needs_init) {
          _this->_impl_.result_.ok_.InitDefault();
        }
        _this->_impl_.result_.ok_.Set(from._internal_ok(), arena);
        break;
      }
      case kError: {
        if (oneof_needs_init) {
          _this->_impl_.result_.error_.InitDefault();
        }
        _this->_impl_.result_.error_.Set(from._internal_error(), arena);
        break;
      }
      case RESULT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Shutdown::CopyFrom(const Shutdown& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:application.Shutdown)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Shutdown::InternalSwap(Shutdown* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Shutdown::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace application
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_params_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
