// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proApiV1Prop.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Rv_Data_API_v1_Transition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uuid: String = String()

  public var name: String = String()

  public var duration: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Rv_Data_API_v1_PropData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Rv_Data_API_v1_Identifier {
    get {_id ?? Rv_Data_API_v1_Identifier()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var isActive: Bool = false

  public var autoClearEnabled: Bool = false

  public var autoClearDuration: Double = 0

  public var transition: Rv_Data_API_v1_Transition {
    get {_transition ?? Rv_Data_API_v1_Transition()}
    set {_transition = newValue}
  }
  /// Returns true if `transition` has been explicitly set.
  public var hasTransition: Bool {self._transition != nil}
  /// Clears the value of `transition`. Subsequent reads from it will return its default value.
  public mutating func clearTransition() {self._transition = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: Rv_Data_API_v1_Identifier? = nil
  fileprivate var _transition: Rv_Data_API_v1_Transition? = nil
}

public struct Rv_Data_API_v1_PropCollection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Rv_Data_API_v1_Identifier {
    get {_id ?? Rv_Data_API_v1_Identifier()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var props: [Rv_Data_API_v1_PropData] = []

  public var singlePropEnabled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: Rv_Data_API_v1_Identifier? = nil
}

public struct Rv_Data_API_v1_Prop_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var request: Rv_Data_API_v1_Prop_Request.OneOf_Request? = nil

  public var props: Rv_Data_API_v1_Prop_Request.Props {
    get {
      if case .props(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.Props()
    }
    set {request = .props(newValue)}
  }

  public var getProp: Rv_Data_API_v1_Prop_Request.GetProp {
    get {
      if case .getProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.GetProp()
    }
    set {request = .getProp(newValue)}
  }

  public var putProp: Rv_Data_API_v1_Prop_Request.PutProp {
    get {
      if case .putProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.PutProp()
    }
    set {request = .putProp(newValue)}
  }

  public var deleteProp: Rv_Data_API_v1_Prop_Request.DeleteProp {
    get {
      if case .deleteProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.DeleteProp()
    }
    set {request = .deleteProp(newValue)}
  }

  public var triggerProp: Rv_Data_API_v1_Prop_Request.TriggerProp {
    get {
      if case .triggerProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.TriggerProp()
    }
    set {request = .triggerProp(newValue)}
  }

  public var clearProp_p: Rv_Data_API_v1_Prop_Request.ClearProp {
    get {
      if case .clearProp_p(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.ClearProp()
    }
    set {request = .clearProp_p(newValue)}
  }

  public var getThumbnail: Rv_Data_API_v1_Prop_Request.GetThumbnail {
    get {
      if case .getThumbnail(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.GetThumbnail()
    }
    set {request = .getThumbnail(newValue)}
  }

  public var getPropCollections: Rv_Data_API_v1_Prop_Request.GetPropCollections {
    get {
      if case .getPropCollections(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.GetPropCollections()
    }
    set {request = .getPropCollections(newValue)}
  }

  public var getPropCollection: Rv_Data_API_v1_Prop_Request.GetPropCollection {
    get {
      if case .getPropCollection(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.GetPropCollection()
    }
    set {request = .getPropCollection(newValue)}
  }

  public var postPropCollections: Rv_Data_API_v1_Prop_Request.PostPropCollections {
    get {
      if case .postPropCollections(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.PostPropCollections()
    }
    set {request = .postPropCollections(newValue)}
  }

  public var putPropCollection: Rv_Data_API_v1_Prop_Request.PutPropCollection {
    get {
      if case .putPropCollection(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.PutPropCollection()
    }
    set {request = .putPropCollection(newValue)}
  }

  public var deletePropCollection: Rv_Data_API_v1_Prop_Request.DeletePropCollection {
    get {
      if case .deletePropCollection(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.DeletePropCollection()
    }
    set {request = .deletePropCollection(newValue)}
  }

  public var pauseProp: Rv_Data_API_v1_Prop_Request.PauseProp {
    get {
      if case .pauseProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.PauseProp()
    }
    set {request = .pauseProp(newValue)}
  }

  public var resumeProp: Rv_Data_API_v1_Prop_Request.ResumeProp {
    get {
      if case .resumeProp(let v)? = request {return v}
      return Rv_Data_API_v1_Prop_Request.ResumeProp()
    }
    set {request = .resumeProp(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Request: Equatable, Sendable {
    case props(Rv_Data_API_v1_Prop_Request.Props)
    case getProp(Rv_Data_API_v1_Prop_Request.GetProp)
    case putProp(Rv_Data_API_v1_Prop_Request.PutProp)
    case deleteProp(Rv_Data_API_v1_Prop_Request.DeleteProp)
    case triggerProp(Rv_Data_API_v1_Prop_Request.TriggerProp)
    case clearProp_p(Rv_Data_API_v1_Prop_Request.ClearProp)
    case getThumbnail(Rv_Data_API_v1_Prop_Request.GetThumbnail)
    case getPropCollections(Rv_Data_API_v1_Prop_Request.GetPropCollections)
    case getPropCollection(Rv_Data_API_v1_Prop_Request.GetPropCollection)
    case postPropCollections(Rv_Data_API_v1_Prop_Request.PostPropCollections)
    case putPropCollection(Rv_Data_API_v1_Prop_Request.PutPropCollection)
    case deletePropCollection(Rv_Data_API_v1_Prop_Request.DeletePropCollection)
    case pauseProp(Rv_Data_API_v1_Prop_Request.PauseProp)
    case resumeProp(Rv_Data_API_v1_Prop_Request.ResumeProp)

  }

  public struct Props: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct PutProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var nameChange: String = String()

    public var autoClearChange: Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange {
      get {_autoClearChange ?? Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange()}
      set {_autoClearChange = newValue}
    }
    /// Returns true if `autoClearChange` has been explicitly set.
    public var hasAutoClearChange: Bool {self._autoClearChange != nil}
    /// Clears the value of `autoClearChange`. Subsequent reads from it will return its default value.
    public mutating func clearAutoClearChange() {self._autoClearChange = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct AutoClearChange: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var autoClearEnabled: Bool = false

      public var autoClearDuration: Double = 0

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }

    public init() {}

    fileprivate var _autoClearChange: Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange? = nil
  }

  public struct DeleteProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct TriggerProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ClearProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct PauseProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ResumeProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetThumbnail: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var quality: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetPropCollections: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetPropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct PostPropCollections: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var name: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct PutPropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var changes: Rv_Data_API_v1_PropCollection {
      get {_changes ?? Rv_Data_API_v1_PropCollection()}
      set {_changes = newValue}
    }
    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {self._changes != nil}
    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {self._changes = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Rv_Data_API_v1_PropCollection? = nil
  }

  public struct DeletePropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

public struct Rv_Data_API_v1_Prop_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var response: Rv_Data_API_v1_Prop_Response.OneOf_Response? = nil

  public var props: Rv_Data_API_v1_Prop_Response.Props {
    get {
      if case .props(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.Props()
    }
    set {response = .props(newValue)}
  }

  public var getProp: Rv_Data_API_v1_Prop_Response.GetProp {
    get {
      if case .getProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.GetProp()
    }
    set {response = .getProp(newValue)}
  }

  public var putProp: Rv_Data_API_v1_Prop_Response.PutProp {
    get {
      if case .putProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.PutProp()
    }
    set {response = .putProp(newValue)}
  }

  public var deleteProp: Rv_Data_API_v1_Prop_Response.DeleteProp {
    get {
      if case .deleteProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.DeleteProp()
    }
    set {response = .deleteProp(newValue)}
  }

  public var triggerProp: Rv_Data_API_v1_Prop_Response.TriggerProp {
    get {
      if case .triggerProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.TriggerProp()
    }
    set {response = .triggerProp(newValue)}
  }

  public var clearProp_p: Rv_Data_API_v1_Prop_Response.ClearProp {
    get {
      if case .clearProp_p(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.ClearProp()
    }
    set {response = .clearProp_p(newValue)}
  }

  public var getThumbnail: Rv_Data_API_v1_Prop_Response.GetThumbnail {
    get {
      if case .getThumbnail(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.GetThumbnail()
    }
    set {response = .getThumbnail(newValue)}
  }

  public var getPropCollections: Rv_Data_API_v1_Prop_Response.GetPropCollections {
    get {
      if case .getPropCollections(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.GetPropCollections()
    }
    set {response = .getPropCollections(newValue)}
  }

  public var getPropCollection: Rv_Data_API_v1_Prop_Response.GetPropCollection {
    get {
      if case .getPropCollection(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.GetPropCollection()
    }
    set {response = .getPropCollection(newValue)}
  }

  public var postPropCollections: Rv_Data_API_v1_Prop_Response.PostPropCollections {
    get {
      if case .postPropCollections(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.PostPropCollections()
    }
    set {response = .postPropCollections(newValue)}
  }

  public var putPropCollection: Rv_Data_API_v1_Prop_Response.PutPropCollection {
    get {
      if case .putPropCollection(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.PutPropCollection()
    }
    set {response = .putPropCollection(newValue)}
  }

  public var deletePropCollection: Rv_Data_API_v1_Prop_Response.DeletePropCollection {
    get {
      if case .deletePropCollection(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.DeletePropCollection()
    }
    set {response = .deletePropCollection(newValue)}
  }

  public var pauseProp: Rv_Data_API_v1_Prop_Response.PauseProp {
    get {
      if case .pauseProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.PauseProp()
    }
    set {response = .pauseProp(newValue)}
  }

  public var resumeProp: Rv_Data_API_v1_Prop_Response.ResumeProp {
    get {
      if case .resumeProp(let v)? = response {return v}
      return Rv_Data_API_v1_Prop_Response.ResumeProp()
    }
    set {response = .resumeProp(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Response: Equatable, Sendable {
    case props(Rv_Data_API_v1_Prop_Response.Props)
    case getProp(Rv_Data_API_v1_Prop_Response.GetProp)
    case putProp(Rv_Data_API_v1_Prop_Response.PutProp)
    case deleteProp(Rv_Data_API_v1_Prop_Response.DeleteProp)
    case triggerProp(Rv_Data_API_v1_Prop_Response.TriggerProp)
    case clearProp_p(Rv_Data_API_v1_Prop_Response.ClearProp)
    case getThumbnail(Rv_Data_API_v1_Prop_Response.GetThumbnail)
    case getPropCollections(Rv_Data_API_v1_Prop_Response.GetPropCollections)
    case getPropCollection(Rv_Data_API_v1_Prop_Response.GetPropCollection)
    case postPropCollections(Rv_Data_API_v1_Prop_Response.PostPropCollections)
    case putPropCollection(Rv_Data_API_v1_Prop_Response.PutPropCollection)
    case deletePropCollection(Rv_Data_API_v1_Prop_Response.DeletePropCollection)
    case pauseProp(Rv_Data_API_v1_Prop_Response.PauseProp)
    case resumeProp(Rv_Data_API_v1_Prop_Response.ResumeProp)

  }

  public struct Props: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var props: [Rv_Data_API_v1_PropData] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var prop: Rv_Data_API_v1_PropData {
      get {_prop ?? Rv_Data_API_v1_PropData()}
      set {_prop = newValue}
    }
    /// Returns true if `prop` has been explicitly set.
    public var hasProp: Bool {self._prop != nil}
    /// Clears the value of `prop`. Subsequent reads from it will return its default value.
    public mutating func clearProp() {self._prop = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _prop: Rv_Data_API_v1_PropData? = nil
  }

  public struct PutProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var prop: Rv_Data_API_v1_PropData {
      get {_prop ?? Rv_Data_API_v1_PropData()}
      set {_prop = newValue}
    }
    /// Returns true if `prop` has been explicitly set.
    public var hasProp: Bool {self._prop != nil}
    /// Clears the value of `prop`. Subsequent reads from it will return its default value.
    public mutating func clearProp() {self._prop = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _prop: Rv_Data_API_v1_PropData? = nil
  }

  public struct DeleteProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct TriggerProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ClearProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct PauseProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct ResumeProp: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetThumbnail: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var data: Data = Data()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public struct GetPropCollections: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var propCollections: Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections {
      get {_propCollections ?? Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections()}
      set {_propCollections = newValue}
    }
    /// Returns true if `propCollections` has been explicitly set.
    public var hasPropCollections: Bool {self._propCollections != nil}
    /// Clears the value of `propCollections`. Subsequent reads from it will return its default value.
    public mutating func clearPropCollections() {self._propCollections = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct Collections: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var collections: [Rv_Data_API_v1_PropCollection] = []

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }

    public init() {}

    fileprivate var _propCollections: Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections? = nil
  }

  public struct GetPropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var propCollection: Rv_Data_API_v1_PropCollection {
      get {_propCollection ?? Rv_Data_API_v1_PropCollection()}
      set {_propCollection = newValue}
    }
    /// Returns true if `propCollection` has been explicitly set.
    public var hasPropCollection: Bool {self._propCollection != nil}
    /// Clears the value of `propCollection`. Subsequent reads from it will return its default value.
    public mutating func clearPropCollection() {self._propCollection = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _propCollection: Rv_Data_API_v1_PropCollection? = nil
  }

  public struct PostPropCollections: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var propCollection: Rv_Data_API_v1_PropCollection {
      get {_propCollection ?? Rv_Data_API_v1_PropCollection()}
      set {_propCollection = newValue}
    }
    /// Returns true if `propCollection` has been explicitly set.
    public var hasPropCollection: Bool {self._propCollection != nil}
    /// Clears the value of `propCollection`. Subsequent reads from it will return its default value.
    public mutating func clearPropCollection() {self._propCollection = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _propCollection: Rv_Data_API_v1_PropCollection? = nil
  }

  public struct PutPropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var propCollection: Rv_Data_API_v1_PropCollection {
      get {_propCollection ?? Rv_Data_API_v1_PropCollection()}
      set {_propCollection = newValue}
    }
    /// Returns true if `propCollection` has been explicitly set.
    public var hasPropCollection: Bool {self._propCollection != nil}
    /// Clears the value of `propCollection`. Subsequent reads from it will return its default value.
    public mutating func clearPropCollection() {self._propCollection = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _propCollection: Rv_Data_API_v1_PropCollection? = nil
  }

  public struct DeletePropCollection: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rv.data"

extension Rv_Data_API_v1_Transition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".API_v1_Transition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uuid\0\u{1}name\0\u{1}duration\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uuid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.duration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uuid.isEmpty {
      try visitor.visitSingularStringField(value: self.uuid, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.duration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Transition, rhs: Rv_Data_API_v1_Transition) -> Bool {
    if lhs.uuid != rhs.uuid {return false}
    if lhs.name != rhs.name {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_PropData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".API_v1_PropData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}is_active\0\u{3}auto_clear_enabled\0\u{3}auto_clear_duration\0\u{1}transition\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isActive) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.autoClearEnabled) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.autoClearDuration) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._transition) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.isActive != false {
      try visitor.visitSingularBoolField(value: self.isActive, fieldNumber: 2)
    }
    if self.autoClearEnabled != false {
      try visitor.visitSingularBoolField(value: self.autoClearEnabled, fieldNumber: 3)
    }
    if self.autoClearDuration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.autoClearDuration, fieldNumber: 4)
    }
    try { if let v = self._transition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_PropData, rhs: Rv_Data_API_v1_PropData) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs.isActive != rhs.isActive {return false}
    if lhs.autoClearEnabled != rhs.autoClearEnabled {return false}
    if lhs.autoClearDuration != rhs.autoClearDuration {return false}
    if lhs._transition != rhs._transition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_PropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".API_v1_PropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}props\0\u{3}single_prop_enabled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._id) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.props) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.singlePropEnabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.props.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.props, fieldNumber: 2)
    }
    if self.singlePropEnabled != false {
      try visitor.visitSingularBoolField(value: self.singlePropEnabled, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_PropCollection, rhs: Rv_Data_API_v1_PropCollection) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs.props != rhs.props {return false}
    if lhs.singlePropEnabled != rhs.singlePropEnabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".API_v1_Prop_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}props\0\u{3}get_prop\0\u{3}put_prop\0\u{3}delete_prop\0\u{3}trigger_prop\0\u{3}clear_prop\0\u{3}get_thumbnail\0\u{3}get_prop_collections\0\u{3}get_prop_collection\0\u{3}post_prop_collections\0\u{3}put_prop_collection\0\u{3}delete_prop_collection\0\u{3}pause_prop\0\u{3}resume_prop\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Rv_Data_API_v1_Prop_Request.Props?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .props(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .props(v)
        }
      }()
      case 2: try {
        var v: Rv_Data_API_v1_Prop_Request.GetProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getProp(v)
        }
      }()
      case 3: try {
        var v: Rv_Data_API_v1_Prop_Request.PutProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .putProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .putProp(v)
        }
      }()
      case 4: try {
        var v: Rv_Data_API_v1_Prop_Request.DeleteProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .deleteProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .deleteProp(v)
        }
      }()
      case 5: try {
        var v: Rv_Data_API_v1_Prop_Request.TriggerProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .triggerProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .triggerProp(v)
        }
      }()
      case 6: try {
        var v: Rv_Data_API_v1_Prop_Request.ClearProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .clearProp_p(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .clearProp_p(v)
        }
      }()
      case 7: try {
        var v: Rv_Data_API_v1_Prop_Request.GetThumbnail?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getThumbnail(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getThumbnail(v)
        }
      }()
      case 8: try {
        var v: Rv_Data_API_v1_Prop_Request.GetPropCollections?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getPropCollections(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getPropCollections(v)
        }
      }()
      case 9: try {
        var v: Rv_Data_API_v1_Prop_Request.GetPropCollection?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getPropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getPropCollection(v)
        }
      }()
      case 10: try {
        var v: Rv_Data_API_v1_Prop_Request.PostPropCollections?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .postPropCollections(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .postPropCollections(v)
        }
      }()
      case 11: try {
        var v: Rv_Data_API_v1_Prop_Request.PutPropCollection?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .putPropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .putPropCollection(v)
        }
      }()
      case 12: try {
        var v: Rv_Data_API_v1_Prop_Request.DeletePropCollection?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .deletePropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .deletePropCollection(v)
        }
      }()
      case 13: try {
        var v: Rv_Data_API_v1_Prop_Request.PauseProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .pauseProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .pauseProp(v)
        }
      }()
      case 14: try {
        var v: Rv_Data_API_v1_Prop_Request.ResumeProp?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .resumeProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .resumeProp(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.request {
    case .props?: try {
      guard case .props(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getProp?: try {
      guard case .getProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .putProp?: try {
      guard case .putProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .deleteProp?: try {
      guard case .deleteProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .triggerProp?: try {
      guard case .triggerProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .clearProp_p?: try {
      guard case .clearProp_p(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .getThumbnail?: try {
      guard case .getThumbnail(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .getPropCollections?: try {
      guard case .getPropCollections(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .getPropCollection?: try {
      guard case .getPropCollection(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .postPropCollections?: try {
      guard case .postPropCollections(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .putPropCollection?: try {
      guard case .putPropCollection(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .deletePropCollection?: try {
      guard case .deletePropCollection(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .pauseProp?: try {
      guard case .pauseProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .resumeProp?: try {
      guard case .resumeProp(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request, rhs: Rv_Data_API_v1_Prop_Request) -> Bool {
    if lhs.request != rhs.request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.Props: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".Props"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.Props, rhs: Rv_Data_API_v1_Prop_Request.Props) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.GetProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".GetProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.GetProp, rhs: Rv_Data_API_v1_Prop_Request.GetProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.PutProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".PutProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}name_change\0\u{3}auto_clear_change\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nameChange) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._autoClearChange) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.nameChange.isEmpty {
      try visitor.visitSingularStringField(value: self.nameChange, fieldNumber: 2)
    }
    try { if let v = self._autoClearChange {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.PutProp, rhs: Rv_Data_API_v1_Prop_Request.PutProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.nameChange != rhs.nameChange {return false}
    if lhs._autoClearChange != rhs._autoClearChange {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.PutProp.protoMessageName + ".AutoClearChange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}auto_clear_enabled\0\u{3}auto_clear_duration\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.autoClearEnabled) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.autoClearDuration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.autoClearEnabled != false {
      try visitor.visitSingularBoolField(value: self.autoClearEnabled, fieldNumber: 1)
    }
    if self.autoClearDuration.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.autoClearDuration, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange, rhs: Rv_Data_API_v1_Prop_Request.PutProp.AutoClearChange) -> Bool {
    if lhs.autoClearEnabled != rhs.autoClearEnabled {return false}
    if lhs.autoClearDuration != rhs.autoClearDuration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.DeleteProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".DeleteProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.DeleteProp, rhs: Rv_Data_API_v1_Prop_Request.DeleteProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.TriggerProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".TriggerProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.TriggerProp, rhs: Rv_Data_API_v1_Prop_Request.TriggerProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.ClearProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".ClearProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.ClearProp, rhs: Rv_Data_API_v1_Prop_Request.ClearProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.PauseProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".PauseProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.PauseProp, rhs: Rv_Data_API_v1_Prop_Request.PauseProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.ResumeProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".ResumeProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.ResumeProp, rhs: Rv_Data_API_v1_Prop_Request.ResumeProp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.GetThumbnail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".GetThumbnail"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}quality\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.quality) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.quality != 0 {
      try visitor.visitSingularInt32Field(value: self.quality, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.GetThumbnail, rhs: Rv_Data_API_v1_Prop_Request.GetThumbnail) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.quality != rhs.quality {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.GetPropCollections: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".GetPropCollections"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.GetPropCollections, rhs: Rv_Data_API_v1_Prop_Request.GetPropCollections) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.GetPropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".GetPropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.GetPropCollection, rhs: Rv_Data_API_v1_Prop_Request.GetPropCollection) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.PostPropCollections: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".PostPropCollections"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.PostPropCollections, rhs: Rv_Data_API_v1_Prop_Request.PostPropCollections) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.PutPropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".PutPropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}changes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._changes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try { if let v = self._changes {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.PutPropCollection, rhs: Rv_Data_API_v1_Prop_Request.PutPropCollection) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs._changes != rhs._changes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Request.DeletePropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Request.protoMessageName + ".DeletePropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Request.DeletePropCollection, rhs: Rv_Data_API_v1_Prop_Request.DeletePropCollection) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".API_v1_Prop_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}props\0\u{3}get_prop\0\u{3}put_prop\0\u{3}delete_prop\0\u{3}trigger_prop\0\u{3}clear_prop\0\u{3}get_thumbnail\0\u{3}get_prop_collections\0\u{3}get_prop_collection\0\u{3}post_prop_collections\0\u{3}put_prop_collection\0\u{3}delete_prop_collection\0\u{3}pause_prop\0\u{3}resume_prop\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Rv_Data_API_v1_Prop_Response.Props?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .props(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .props(v)
        }
      }()
      case 2: try {
        var v: Rv_Data_API_v1_Prop_Response.GetProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getProp(v)
        }
      }()
      case 3: try {
        var v: Rv_Data_API_v1_Prop_Response.PutProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .putProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .putProp(v)
        }
      }()
      case 4: try {
        var v: Rv_Data_API_v1_Prop_Response.DeleteProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .deleteProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .deleteProp(v)
        }
      }()
      case 5: try {
        var v: Rv_Data_API_v1_Prop_Response.TriggerProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .triggerProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .triggerProp(v)
        }
      }()
      case 6: try {
        var v: Rv_Data_API_v1_Prop_Response.ClearProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .clearProp_p(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .clearProp_p(v)
        }
      }()
      case 7: try {
        var v: Rv_Data_API_v1_Prop_Response.GetThumbnail?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getThumbnail(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getThumbnail(v)
        }
      }()
      case 8: try {
        var v: Rv_Data_API_v1_Prop_Response.GetPropCollections?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getPropCollections(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getPropCollections(v)
        }
      }()
      case 9: try {
        var v: Rv_Data_API_v1_Prop_Response.GetPropCollection?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getPropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getPropCollection(v)
        }
      }()
      case 10: try {
        var v: Rv_Data_API_v1_Prop_Response.PostPropCollections?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .postPropCollections(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .postPropCollections(v)
        }
      }()
      case 11: try {
        var v: Rv_Data_API_v1_Prop_Response.PutPropCollection?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .putPropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .putPropCollection(v)
        }
      }()
      case 12: try {
        var v: Rv_Data_API_v1_Prop_Response.DeletePropCollection?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .deletePropCollection(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .deletePropCollection(v)
        }
      }()
      case 13: try {
        var v: Rv_Data_API_v1_Prop_Response.PauseProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .pauseProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .pauseProp(v)
        }
      }()
      case 14: try {
        var v: Rv_Data_API_v1_Prop_Response.ResumeProp?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .resumeProp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .resumeProp(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .props?: try {
      guard case .props(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getProp?: try {
      guard case .getProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .putProp?: try {
      guard case .putProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .deleteProp?: try {
      guard case .deleteProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .triggerProp?: try {
      guard case .triggerProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .clearProp_p?: try {
      guard case .clearProp_p(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .getThumbnail?: try {
      guard case .getThumbnail(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .getPropCollections?: try {
      guard case .getPropCollections(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .getPropCollection?: try {
      guard case .getPropCollection(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .postPropCollections?: try {
      guard case .postPropCollections(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .putPropCollection?: try {
      guard case .putPropCollection(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .deletePropCollection?: try {
      guard case .deletePropCollection(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .pauseProp?: try {
      guard case .pauseProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .resumeProp?: try {
      guard case .resumeProp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response, rhs: Rv_Data_API_v1_Prop_Response) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.Props: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".Props"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}props\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.props) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.props.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.props, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.Props, rhs: Rv_Data_API_v1_Prop_Response.Props) -> Bool {
    if lhs.props != rhs.props {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.GetProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".GetProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prop\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._prop) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._prop {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.GetProp, rhs: Rv_Data_API_v1_Prop_Response.GetProp) -> Bool {
    if lhs._prop != rhs._prop {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.PutProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".PutProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prop\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._prop) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._prop {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.PutProp, rhs: Rv_Data_API_v1_Prop_Response.PutProp) -> Bool {
    if lhs._prop != rhs._prop {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.DeleteProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".DeleteProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.DeleteProp, rhs: Rv_Data_API_v1_Prop_Response.DeleteProp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.TriggerProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".TriggerProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.TriggerProp, rhs: Rv_Data_API_v1_Prop_Response.TriggerProp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.ClearProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".ClearProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.ClearProp, rhs: Rv_Data_API_v1_Prop_Response.ClearProp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.PauseProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".PauseProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.PauseProp, rhs: Rv_Data_API_v1_Prop_Response.PauseProp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.ResumeProp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".ResumeProp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.ResumeProp, rhs: Rv_Data_API_v1_Prop_Response.ResumeProp) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.GetThumbnail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".GetThumbnail"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.GetThumbnail, rhs: Rv_Data_API_v1_Prop_Response.GetThumbnail) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.GetPropCollections: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".GetPropCollections"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prop_collections\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._propCollections) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._propCollections {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.GetPropCollections, rhs: Rv_Data_API_v1_Prop_Response.GetPropCollections) -> Bool {
    if lhs._propCollections != rhs._propCollections {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.GetPropCollections.protoMessageName + ".Collections"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}collections\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.collections) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.collections.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.collections, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections, rhs: Rv_Data_API_v1_Prop_Response.GetPropCollections.Collections) -> Bool {
    if lhs.collections != rhs.collections {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.GetPropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".GetPropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prop_collection\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._propCollection) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._propCollection {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.GetPropCollection, rhs: Rv_Data_API_v1_Prop_Response.GetPropCollection) -> Bool {
    if lhs._propCollection != rhs._propCollection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.PostPropCollections: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".PostPropCollections"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prop_collection\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._propCollection) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._propCollection {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.PostPropCollections, rhs: Rv_Data_API_v1_Prop_Response.PostPropCollections) -> Bool {
    if lhs._propCollection != rhs._propCollection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.PutPropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".PutPropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prop_collection\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._propCollection) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._propCollection {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.PutPropCollection, rhs: Rv_Data_API_v1_Prop_Response.PutPropCollection) -> Bool {
    if lhs._propCollection != rhs._propCollection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rv_Data_API_v1_Prop_Response.DeletePropCollection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Rv_Data_API_v1_Prop_Response.protoMessageName + ".DeletePropCollection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Rv_Data_API_v1_Prop_Response.DeletePropCollection, rhs: Rv_Data_API_v1_Prop_Response.DeletePropCollection) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
